jpos_default: [0, 0, -0.5, 1.0, -0.5, 0, 0, 
               0, 0, 0, 0, 0, 0, 0, 
               0, 
               0, 0, 0, 0,
               0, 0, 0, 0]
swing_freq: [ 0, 0, 0.5, 0.5, 0.5, 0, 0, 
              0, 0, 0, 0, 0, 0, 0, 
              0, 
              0, 0, 0, 0,
              0, 0, 0, 0]
swing_amp: [0, 0, 0.5, 0.5, 0.5, 0, 0, 
            0, 0, 0, 0, 0, 0, 0, 
            0, 
            0, 0, 0, 0,
            0, 0, 0, 0]
