function gravity = grav_biped(in1)
%GRAV_BIPED
%    GRAVITY = GRAV_BIPED(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    11-Jul-2024 13:47:36

q_ankle_l = in1(10,:);
q_ankle_r = in1(6,:);
q_hip_l = in1(8,:);
q_hip_r = in1(4,:);
q_knee_l = in1(9,:);
q_knee_r = in1(5,:);
q_toe_l = in1(11,:);
q_toe_r = in1(7,:);
th = in1(3,:);
t2 = q_hip_l+th;
t3 = q_hip_r+th;
t10 = atan(5.5e+1./2.4e+1);
t15 = 6.000833275470999e+1;
t4 = q_knee_l+t2;
t5 = q_knee_r+t3;
t6 = sin(t2);
t7 = sin(t3);
t16 = -t10;
t8 = sin(t4);
t9 = sin(t5);
t11 = q_ankle_l+q_toe_l+t4;
t12 = q_ankle_r+q_toe_r+t5;
t17 = q_ankle_l+t4+t16;
t18 = q_ankle_r+t5+t16;
t21 = t6.*1.70694e+1;
t22 = t7.*1.70694e+1;
t13 = sin(t11);
t14 = sin(t12);
t19 = cos(t17);
t20 = cos(t18);
t23 = t8.*5.6898;
t24 = t9.*5.6898;
t25 = t13.*1.962e-2;
t26 = t14.*1.962e-2;
t27 = t15.*t19.*3.924e-3;
t28 = t15.*t20.*3.924e-3;
gravity = [0.0;2.8449e+2;t21+t22+t23+t24+t25+t26+t27+t28-sin(th).*2.943e+1;t22+t24+t26+t28;t24+t26+t28;t26+t28;t26;t21+t23+t25+t27;t23+t25+t27;t25+t27;t25];
