function J_contact = J_biped(in1)
%J_BIPED
%    J_CONTACT = J_BIPED(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    15-Jul-2024 01:50:15

q_ankle = in1(5,:);
q_hip = in1(3,:);
q_knee = in1(4,:);
t2 = cos(q_hip);
t3 = sin(q_hip);
t4 = q_hip+q_knee;
t5 = cos(t4);
t6 = q_ankle+t4;
t7 = sin(t4);
t12 = t2.*(6.9e+1./2.0e+2);
t13 = t3.*(6.9e+1./2.0e+2);
t8 = cos(t6);
t9 = sin(t6);
t17 = t5.*(7.1e+1./2.0e+2);
t18 = t7.*(7.1e+1./2.0e+2);
t10 = t8./5.0;
t11 = t9./5.0;
t14 = t8.*(3.0./5.0e+1);
t16 = t9.*(3.0./5.0e+1);
t19 = t8.*(9.0./2.0e+2);
t20 = t9.*(9.0./2.0e+2);
t15 = -t11;
t21 = -t19;
J_contact = reshape([1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,t12+t14+t17+t20,t13+t16+t18+t21,t12+t14+t15+t17,t10+t13+t16+t18,t14+t17+t20,t16+t18+t21,t14+t15+t17,t10+t16+t18,t14+t20,t16+t21,t14+t15,t10+t16],[4,5]);
