function keypoints = keypoints_biped(in1)
%KEYPOINTS_BIPED
%    KEYPOINTS = KEYPOINTS_BIPED(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    15-Jul-2024 01:50:15

q_ankle = in1(5,:);
q_hip = in1(3,:);
q_knee = in1(4,:);
x = in1(1,:);
y = in1(2,:);
t2 = cos(q_hip);
t3 = sin(q_hip);
t4 = q_hip+q_knee;
t5 = cos(t4);
t6 = q_ankle+t4;
t7 = sin(t4);
t10 = t2.*(6.9e+1./2.0e+2);
t11 = t3.*(6.9e+1./2.0e+2);
t8 = cos(t6);
t9 = sin(t6);
t14 = -t10;
t16 = t5.*(7.1e+1./2.0e+2);
t17 = t7.*(7.1e+1./2.0e+2);
t12 = t8.*(3.0./5.0e+1);
t13 = t9.*(3.0./5.0e+1);
t18 = -t16;
t15 = -t12;
keypoints = reshape([x,y,t11+x,t14+y,t11+t17+x,t14+t18+y,t8.*(-9.0./2.0e+2)+t11+t13+t17+x,t9.*(-9.0./2.0e+2)+t14+t15+t18+y,t8./5.0+t11+t13+t17+x,t9./5.0+t14+t15+t18+y],[2,5]);
