function keypoints_vel = keypoints_vel_biped(in1)
%KEYPOINTS_VEL_BIPED
%    KEYPOINTS_VEL = KEYPOINTS_VEL_BIPED(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    15-Jul-2024 01:48:31

dq_hip = in1(8,:);
dq_knee = in1(9,:);
dq_ankle = in1(10,:);
dx = in1(6,:);
dy = in1(7,:);
q_ankle = in1(5,:);
q_hip = in1(3,:);
q_knee = in1(4,:);
t2 = cos(q_hip);
t3 = sin(q_hip);
t4 = q_hip+q_knee;
t5 = cos(t4);
t6 = q_ankle+t4;
t7 = sin(t4);
t12 = t2.*(6.9e+1./2.0e+2);
t13 = t3.*(6.9e+1./2.0e+2);
t8 = cos(t6);
t9 = sin(t6);
t17 = t5.*(7.1e+1./2.0e+2);
t18 = t7.*(7.1e+1./2.0e+2);
t10 = t8./5.0;
t11 = t9./5.0;
t14 = t8.*(3.0./5.0e+1);
t16 = t9.*(3.0./5.0e+1);
t19 = t8.*(9.0./2.0e+2);
t20 = t9.*(9.0./2.0e+2);
t15 = -t11;
t21 = -t19;
keypoints_vel = reshape([dx,dy,dx+dq_hip.*t12,dy+dq_hip.*t13,dx+dq_hip.*(t12+t17)+dq_knee.*t17,dy+dq_hip.*(t13+t18)+dq_knee.*t18,dx+dq_ankle.*(t14+t20)+dq_knee.*(t14+t17+t20)+dq_hip.*(t12+t14+t17+t20),dy+dq_ankle.*(t16+t21)+dq_knee.*(t16+t18+t21)+dq_hip.*(t13+t16+t18+t21),dx-dq_ankle.*(t11-t14)+dq_knee.*(t14+t15+t17)+dq_hip.*(t12+t14+t15+t17),dy+dq_ankle.*(t10+t16)+dq_knee.*(t10+t16+t18)+dq_hip.*(t10+t13+t16+t18)],[2,5]);
