target_height     : 0.6

Kp: [100, 
     200.0, 200, 200, 250, 250, 250, 200, 
     200.0, 200, 200, 250, 250, 250, 200, 
     100, 100, 100, 100,
     100, 100, 100, 100]

Kd: [5, 
     5, 5, 5, 15, 15, 15, 5, 
     5, 5, 5, 15, 15, 15, 5, 
     5, 5, 5, 5,
     5, 5, 5, 5]


WBC_Kp_ori            : [150, 150, 150]
WBC_Kd_ori            : [3, 3, 3]
WBC_Kp_body           : [200, 200, 200]
WBC_Kd_body           : [3, 3, 3]
WBC_Kp_joint          : 200
WBC_Kd_joint          : 3

MAX_REACTION_FORCE    : 584.539834      # 18.8114 * 9.81
FloatingBaseWeight    : 0.1
REACTION_FORCE_Z_WEIGHT : 10
REACTION_FORCE_X_WEIGHT : 1