# Robot Configuration
robot_name: "staccatoe"
behavior: "hopping"
horizon: 20
n_contact: 5
dt: 0.05
mu: 0.8

# Dimensions
nq: 12 # 13 for quaternion
nv: 12
nu: 6

# Initial State
q0: [0, 0, 0.75396101, 0, 0, 0, 0, -0.349066, 1.0472, -0.698132, 0.0, 0.0]
v0: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


kinematic_reference_points:
  - body_position: [0.0, 0.0, 0.75396101]
    body_orientation: [0.0, 0.0, 0.0, 1.0]
    time: 0.0
  - body_position: [0.0, 0.0, 0.75396101]
    body_orientation: [0.0, 0.0, 0.0, 1.0]
    time: 0.6
  - body_position: [0.0, 0.0, 0.75396101]
    body_orientation: [0.0, 0.0, 0.0, 1.0]
    time: 1.0

# Bounds
q_min: [-1.57, -1.57, 0.0, -1.3, -0.785, -0.9]
q_max: [1.57, 1.57, 2.66, 1.3, 0.785, 0.9]
vmax: [20.0, 20.0, 20.0, 20.0, 20.0, 10.0]
tau_max: [48.0, 48.0, 100.0, 100.0, 100.0, 10.0]

# Weights
Q_q: [1000, 1000, 10000, 1000, 1000, 1, 1, 1, 1, 1, 1, 1]
Q_v:
  [
    0.001,
    0.001,
    10,
    0.001,
    0.001,
    0.001,
    0.0001,
    0.0001,
    0.0001,
    0.0001,
    0.0001,
    0.0001,
  ]
Q_tau: 0.1
Q_fr: 0.001

contact_modes:
  [
    [1, 1, 1, 1, 1], # 5 contact points 3 modes
    [0, 0, 0, 0, 0],
    [1, 1, 1, 1, 1],
  ]
contact_mode_transition_times: [0.2, 0.6] # transition times between contact modes 2 transitions for 3 modes


# Paths
solver_path: "/home/dan/NMPC-code-generator/results/staccatoe/staccatoe_ref_track_horizon_20_nlp.casadi"
lb_func_path: "/home/dan/NMPC-code-generator/results/staccatoe/staccatoe_ref_track_horizon_20_lb.casadi"
ub_func_path: "/home/dan/NMPC-code-generator/results/staccatoe/staccatoe_ref_track_horizon_20_ub.casadi"


output_path: "/home/dan/NMPC-code-generator/results/staccatoe/"