//
// Academic License - for use in teaching, academic research, and meeting
// course requirements at degree granting institutions only.  Not for
// government, commercial, or other organizational use.
// File: RPCLagrangianHessianFinalSP.cpp
//
// MATLAB Coder version            : 3.2
// C/C++ source code generated on  : 05-Mar-2020 07:55:47
//

// Include Files
#include "RPCBounds.h"
#include "RPCConstraintJacobian.h"
#include "RPCConstraintJacobianFinal.h"
#include "RPCConstraintJacobianFinalSP.h"
#include "RPCConstraintJacobianSP.h"
#include "RPCConstraints.h"
#include "RPCConstraintsFinal.h"
#include "RPCCost.h"
#include "RPCCostGradient.h"
#include "RPCHeuristics.h"
#include "RPCInitialize.h"
#include "RPCLagrangianHessian.h"
#include "RPCLagrangianHessianFinal.h"
#include "RPCLagrangianHessianFinalSP.h"
#include "RPCLagrangianHessianSP.h"

// Function Definitions

//
// RPCLAGRANGIANHESSIANFINALSP
//     [ROW_INDEX_FINAL_H,COL_INDEX_FINAL_H] = RPCLAGRANGIANHESSIANFINALSP(ITER,NUM_X)
// Arguments    : int iter
//                int NUM_X
//                int row_index_final_H[36]
//                int col_index_final_H[36]
// Return Type  : void
//
void RPCLagrangianHessianFinalSP(int iter, int NUM_X, int
  row_index_final_H[36], int col_index_final_H[36])
{
  int t2;

  //     This function was generated by the Symbolic Math Toolbox version 7.1.
  //     05-Mar-2020 07:54:50
  t2 = NUM_X * iter;
  row_index_final_H[0] = t2;
  row_index_final_H[1] = t2 + 1;
  row_index_final_H[2] = t2 + 2;
  row_index_final_H[3] = t2 + 3;
  row_index_final_H[4] = t2 + 4;
  row_index_final_H[5] = t2 + 5;
  row_index_final_H[6] = t2 + 6;
  row_index_final_H[7] = t2 + 7;
  row_index_final_H[8] = t2 + 8;
  row_index_final_H[9] = t2 + 9;
  row_index_final_H[10] = t2 + 10;
  row_index_final_H[11] = t2 + 11;
  row_index_final_H[12] = t2 + 12;
  row_index_final_H[13] = t2 + 13;
  row_index_final_H[14] = t2 + 14;
  row_index_final_H[15] = t2 + 15;
  row_index_final_H[16] = t2 + 16;
  row_index_final_H[17] = t2 + 17;
  row_index_final_H[18] = t2 + 18;
  row_index_final_H[19] = t2 + 19;
  row_index_final_H[20] = t2 + 20;
  row_index_final_H[21] = t2 + 21;
  row_index_final_H[22] = t2 + 22;
  row_index_final_H[23] = t2 + 23;
  row_index_final_H[24] = t2 + 24;
  row_index_final_H[25] = t2 + 25;
  row_index_final_H[26] = t2 + 26;
  row_index_final_H[27] = t2 + 27;
  row_index_final_H[28] = t2 + 28;
  row_index_final_H[29] = t2 + 29;
  row_index_final_H[30] = t2 + 30;
  row_index_final_H[31] = t2 + 31;
  row_index_final_H[32] = t2 + 32;
  row_index_final_H[33] = t2 + 33;
  row_index_final_H[34] = t2 + 34;
  row_index_final_H[35] = t2 + 35;
  memcpy(&col_index_final_H[0], &row_index_final_H[0], 36U * sizeof(int));
}

//
// File trailer for RPCLagrangianHessianFinalSP.cpp
//
// [EOF]
//
