//
// Academic License - for use in teaching, academic research, and meeting
// course requirements at degree granting institutions only.  Not for
// government, commercial, or other organizational use.
// File: RPCLagrangianHessian.cpp
//
// MATLAB Coder version            : 3.2
// C/C++ source code generated on  : 05-Mar-2020 07:55:47
//

// Include Files
#include "RPCBounds.h"
#include "RPCConstraintJacobian.h"
#include "RPCConstraintJacobianFinal.h"
#include "RPCConstraintJacobianFinalSP.h"
#include "RPCConstraintJacobianSP.h"
#include "RPCConstraints.h"
#include "RPCConstraintsFinal.h"
#include "RPCCost.h"
#include "RPCCostGradient.h"
#include "RPCHeuristics.h"
#include "RPCInitialize.h"
#include "RPCLagrangianHessian.h"
#include "RPCLagrangianHessianFinal.h"
#include "RPCLagrangianHessianFinalSP.h"
#include "RPCLagrangianHessianSP.h"

// Function Definitions

//
// RPCLAGRANGIANHESSIAN
//     LAGRANGIAN_HESSIAN_NZ = RPCLAGRANGIANHESSIAN(IN1,IN2,IN3,IN4,IN5,DT,OBJ_FACTOR,IN8,IN9)
// Arguments    : const double in1[12]
//                const double in2[24]
//                const double in3[4]
//                const double in4[12]
//                const double in5[24]
//                double dt
//                double obj_factor
//                const double in8[44]
//                const double in9[3]
//                double lagrangian_hessian_nz[135]
// Return Type  : void
//
void RPCLagrangianHessian(const double in1[12], const double in2[24], const
  double in3[4], const double in4[12], const double in5[24], double dt, double
  obj_factor, const double in8[44], const double in9[3], double
  lagrangian_hessian_nz[135])
{
  double t2;
  double t3;
  double t4;
  double t5;
  double t6;
  double t7;
  double t8;
  double t13;
  double t14;
  double t15;
  double t16;
  double t21;
  double t30;
  double t31;
  double t32;
  double t33;
  double t34;
  double t35;
  double t37;
  double t40;
  double t229;
  double t230;
  double t41;
  double t42;
  double t45;
  double t47;
  double t232;
  double t233;
  double t48;
  double t53;
  double t56;
  double t59;
  double t62;
  double t63;
  double t66;
  double t69;
  double t71;
  double t74;
  double t77;
  double t78;
  double t81;
  double t84;
  double t86;
  double t89;
  double t92;
  double t93;
  double t96;
  double t99;
  double t101;
  double t104;
  double t107;
  double t108;
  double t111;
  double t114;
  double t116;
  double t121;
  double t231;
  double t128;
  double t234;
  double t131;
  double t133;
  double t138;
  double t141;
  double t143;
  double t146;
  double t149;
  double t154;
  double t156;
  double t159;
  double t162;
  double t165;
  double t167;
  double t170;
  double t173;
  double t176;
  double t178;
  double t181;
  double t184;
  double t187;
  double t189;
  double t192;
  double t195;
  double t198;
  double t200;
  double t203;
  double t206;
  double t209;
  double t211;
  double t214;
  double t217;
  double t220;
  double t222;
  double t225;
  double t228;
  double t235;
  double t261;
  double t264;
  double t266;
  double t268;
  double t271;
  double t273;
  double t276;
  double t278;
  double t280;
  double t282;
  double t284;
  double t287;
  double t289;
  double t292;
  double t294;
  double t296;
  double t299;
  double t301;
  double t304;
  double t306;
  double t308;
  double t310;
  double t312;
  double t315;
  double t317;
  double t320;
  double t322;
  double t324;
  double t327;
  double t329;
  double t332;
  double t334;
  double t336;
  double t338;
  double t340;
  double t343;
  double t345;
  double t348;
  double t349;
  double t350;
  double t351;
  double t352;
  double t353;
  double t354;
  double t355;
  double t356;
  double t357;
  double t358;
  double t359;
  double t360;
  double t361;
  double t362;
  double t363;
  double t364;

  //     This function was generated by the Symbolic Math Toolbox version 7.1.
  //     05-Mar-2020 07:54:46
  t2 = in3[0] * in3[0];
  t3 = in3[1] * in3[1];
  t4 = in3[2] * in3[2];
  t5 = in3[3] * in3[3];
  t6 = std::cos(in1[4]);
  t7 = std::sin(in1[3]);
  t8 = std::cos(in1[3]);
  t13 = ((((((in2[3] * in2[1] * t2 + in2[9] * in2[7] * t3) + in2[15] * in2[13] *
             t4) + in2[21] * in2[19] * t5) - in2[4] * in2[0] * t2) - in2[10] *
          in2[6] * t3) - in2[16] * in2[12] * t4) - in2[22] * in2[18] * t5;
  t14 = std::sin(in1[5]);
  t15 = std::cos(in1[5]);
  t16 = std::sin(in1[4]);
  t21 = ((((((in2[3] * in2[2] * t2 + in2[9] * in2[8] * t3) + in2[15] * in2[14] *
             t4) + in2[21] * in2[20] * t5) - in2[5] * in2[0] * t2) - in2[11] *
          in2[6] * t3) - in2[17] * in2[12] * t4) - in2[23] * in2[18] * t5;
  t30 = 1.0 / in9[2];
  t31 = t6 * t8 * t13;
  t32 = t6 * t7 * t21;
  t33 = t31 + t32;
  t34 = 1.0 / in9[0];
  t35 = dt * dt;
  t37 = t7 * t14 - t8 * t15 * t16;
  t40 = t8 * t14 + t7 * t15 * t16;
  t229 = t13 * t37;
  t230 = t21 * t40;
  t41 = t229 - t230;
  t42 = 1.0 / in9[1];
  t45 = t7 * t15 + t8 * t14 * t16;
  t47 = t8 * t15 - t7 * t14 * t16;
  t232 = t13 * t45;
  t233 = t21 * t47;
  t48 = t232 - t233;
  t53 = t13 * t47 + t21 * t45;
  t56 = t13 * t40 + t21 * t37;
  t59 = in2[4] * t2 * t40 + in2[5] * t2 * t37;
  t62 = in2[4] * t2 * t47 + in2[5] * t2 * t45;
  t63 = in2[4] * t7;
  t66 = in2[1] * t2 * t40 + in2[2] * t2 * t37;
  t69 = in2[1] * t2 * t47 + in2[2] * t2 * t45;
  t71 = in2[1] * t7 - in2[2] * t8;
  t74 = in2[10] * t3 * t40 + in2[11] * t3 * t37;
  t77 = in2[10] * t3 * t47 + in2[11] * t3 * t45;
  t78 = in2[10] * t7;
  t81 = in2[7] * t3 * t40 + in2[8] * t3 * t37;
  t84 = in2[7] * t3 * t47 + in2[8] * t3 * t45;
  t86 = in2[7] * t7 - in2[8] * t8;
  t89 = in2[16] * t4 * t40 + in2[17] * t4 * t37;
  t92 = in2[16] * t4 * t47 + in2[17] * t4 * t45;
  t93 = in2[16] * t7;
  t96 = in2[13] * t4 * t40 + in2[14] * t4 * t37;
  t99 = in2[13] * t4 * t47 + in2[14] * t4 * t45;
  t101 = in2[13] * t7 - in2[14] * t8;
  t104 = in2[22] * t5 * t40 + in2[23] * t5 * t37;
  t107 = in2[22] * t5 * t47 + in2[23] * t5 * t45;
  t108 = in2[22] * t7;
  t111 = in2[19] * t5 * t40 + in2[20] * t5 * t37;
  t114 = in2[19] * t5 * t47 + in2[20] * t5 * t45;
  t116 = in2[19] * t7 - in2[20] * t8;
  t121 = ((((((in2[4] * in2[2] * t2 + in2[10] * in2[8] * t3) + in2[16] * in2[14]
              * t4) + in2[22] * in2[20] * t5) - in2[5] * in2[1] * t2) - in2[11] *
           in2[7] * t3) - in2[17] * in2[13] * t4) - in2[23] * in2[19] * t5;
  t231 = t6 * t15 * t121;
  t128 = (t8 * t13 * t15 * t16 + t7 * t15 * t16 * t21) - t231;
  t234 = t6 * t14 * t121;
  t131 = (t8 * t13 * t14 * t16 + t7 * t14 * t16 * t21) - t234;
  t133 = (t31 + t32) + t16 * t121;
  t138 = ((((in9[0] * in9[1] * in8[11] * t16 * 2.0 + in9[1] * in9[2] * in8[9] *
             t6 * t15 * 2.0) + in9[0] * in9[1] * dt * in8[5] * t16) + in9[1] *
           in9[2] * dt * in8[3] * t6 * t15) - in9[0] * in9[2] * in8[10] * t6 *
          t14 * 2.0) - in9[0] * in9[2] * dt * in8[4] * t6 * t14;
  t141 = in2[5] * t6 + in2[3] * t8 * t16;
  t143 = in2[5] * t16 - in2[3] * t6 * t8;
  t146 = in2[4] * t6 - in2[3] * t7 * t16;
  t149 = in2[4] * t16 + in2[3] * t6 * t7;
  t154 = in2[2] * t6 + in2[0] * t8 * t16;
  t156 = in2[2] * t16 - in2[0] * t6 * t8;
  t159 = in2[1] * t6 - in2[0] * t7 * t16;
  t162 = in2[1] * t16 + in2[0] * t6 * t7;
  t165 = in2[11] * t6 + in2[9] * t8 * t16;
  t167 = in2[11] * t16 - in2[9] * t6 * t8;
  t170 = in2[10] * t6 - in2[9] * t7 * t16;
  t173 = in2[10] * t16 + in2[9] * t6 * t7;
  t176 = in2[8] * t6 + in2[6] * t8 * t16;
  t178 = in2[8] * t16 - in2[6] * t6 * t8;
  t181 = in2[7] * t6 - in2[6] * t7 * t16;
  t184 = in2[7] * t16 + in2[6] * t6 * t7;
  t187 = in2[17] * t6 + in2[15] * t8 * t16;
  t189 = in2[17] * t16 - in2[15] * t6 * t8;
  t192 = in2[16] * t6 - in2[15] * t7 * t16;
  t195 = in2[16] * t16 + in2[15] * t6 * t7;
  t198 = in2[14] * t6 + in2[12] * t8 * t16;
  t200 = in2[14] * t16 - in2[12] * t6 * t8;
  t203 = in2[13] * t6 - in2[12] * t7 * t16;
  t206 = in2[13] * t16 + in2[12] * t6 * t7;
  t209 = in2[23] * t6 + in2[21] * t8 * t16;
  t211 = in2[23] * t16 - in2[21] * t6 * t8;
  t214 = in2[22] * t6 - in2[21] * t7 * t16;
  t217 = in2[22] * t16 + in2[21] * t6 * t7;
  t220 = in2[20] * t6 + in2[18] * t8 * t16;
  t222 = in2[20] * t16 - in2[18] * t6 * t8;
  t225 = in2[19] * t6 - in2[18] * t7 * t16;
  t228 = in2[19] * t16 + in2[18] * t6 * t7;
  t235 = (t229 - t230) + t231;
  t13 = (-t232 + t233) + t234;
  t21 = in2[4] * t2 * t45 - in2[5] * t2 * t47;
  t31 = in2[4] * t2 * t37 - in2[5] * t2 * t40;
  t32 = in2[3] * t2 * t45 + in2[5] * t2 * t6 * t14;
  t121 = in2[3] * t2 * t37 - in2[5] * t2 * t6 * t15;
  t229 = in2[3] * t2 * t47 + in2[4] * t2 * t6 * t14;
  t230 = in2[3] * t2 * t40 - in2[4] * t2 * t6 * t15;
  t231 = in2[1] * t2 * t45 - in2[2] * t2 * t47;
  t232 = in2[1] * t2 * t37 - in2[2] * t2 * t40;
  t233 = in2[0] * t2 * t37 - in2[2] * t2 * t6 * t15;
  t234 = in2[0] * t2 * t45 + in2[2] * t2 * t6 * t14;
  t261 = in2[0] * t2 * t40 - in2[1] * t2 * t6 * t15;
  t264 = in2[0] * t2 * t47 + in2[1] * t2 * t6 * t14;
  t266 = in2[10] * t3 * t45 - in2[11] * t3 * t47;
  t268 = in2[10] * t3 * t37 - in2[11] * t3 * t40;
  t271 = in2[9] * t3 * t45 + in2[11] * t3 * t6 * t14;
  t273 = in2[9] * t3 * t37 - in2[11] * t3 * t6 * t15;
  t276 = in2[9] * t3 * t47 + in2[10] * t3 * t6 * t14;
  t278 = in2[9] * t3 * t40 - in2[10] * t3 * t6 * t15;
  t280 = in2[7] * t3 * t45 - in2[8] * t3 * t47;
  t282 = in2[7] * t3 * t37 - in2[8] * t3 * t40;
  t284 = in2[6] * t3 * t37 - in2[8] * t3 * t6 * t15;
  t287 = in2[6] * t3 * t45 + in2[8] * t3 * t6 * t14;
  t289 = in2[6] * t3 * t40 - in2[7] * t3 * t6 * t15;
  t292 = in2[6] * t3 * t47 + in2[7] * t3 * t6 * t14;
  t294 = in2[16] * t4 * t45 - in2[17] * t4 * t47;
  t296 = in2[16] * t4 * t37 - in2[17] * t4 * t40;
  t299 = in2[15] * t4 * t45 + in2[17] * t4 * t6 * t14;
  t301 = in2[15] * t4 * t37 - in2[17] * t4 * t6 * t15;
  t304 = in2[15] * t4 * t47 + in2[16] * t4 * t6 * t14;
  t306 = in2[15] * t4 * t40 - in2[16] * t4 * t6 * t15;
  t308 = in2[13] * t4 * t45 - in2[14] * t4 * t47;
  t310 = in2[13] * t4 * t37 - in2[14] * t4 * t40;
  t312 = in2[12] * t4 * t37 - in2[14] * t4 * t6 * t15;
  t315 = in2[12] * t4 * t45 + in2[14] * t4 * t6 * t14;
  t317 = in2[12] * t4 * t40 - in2[13] * t4 * t6 * t15;
  t320 = in2[12] * t4 * t47 + in2[13] * t4 * t6 * t14;
  t322 = in2[22] * t5 * t45 - in2[23] * t5 * t47;
  t324 = in2[22] * t5 * t37 - in2[23] * t5 * t40;
  t327 = in2[21] * t5 * t45 + in2[23] * t5 * t6 * t14;
  t329 = in2[21] * t5 * t37 - in2[23] * t5 * t6 * t15;
  t332 = in2[21] * t5 * t47 + in2[22] * t5 * t6 * t14;
  t334 = in2[21] * t5 * t40 - in2[22] * t5 * t6 * t15;
  t336 = in2[19] * t5 * t45 - in2[20] * t5 * t47;
  t338 = in2[19] * t5 * t37 - in2[20] * t5 * t40;
  t340 = in2[18] * t5 * t37 - in2[20] * t5 * t6 * t15;
  t343 = in2[18] * t5 * t45 + in2[20] * t5 * t6 * t14;
  t345 = in2[18] * t5 * t40 - in2[19] * t5 * t6 * t15;
  t348 = in2[18] * t5 * t47 + in2[19] * t5 * t6 * t14;
  t349 = dt * in8[9] * t2 * t34 * t40;
  t350 = dt * in8[10] * t2 * t42 * t47;
  t351 = in8[3] * t2 * t34 * t35 * t40 * 0.5;
  t352 = in8[4] * t2 * t35 * t42 * t47 * 0.5;
  t353 = dt * in8[9] * t3 * t34 * t40;
  t354 = dt * in8[10] * t3 * t42 * t47;
  t355 = in8[3] * t3 * t34 * t35 * t40 * 0.5;
  t356 = in8[4] * t3 * t35 * t42 * t47 * 0.5;
  t357 = dt * in8[9] * t4 * t34 * t40;
  t358 = dt * in8[10] * t4 * t42 * t47;
  t359 = in8[3] * t4 * t34 * t35 * t40 * 0.5;
  t360 = in8[4] * t4 * t35 * t42 * t47 * 0.5;
  t361 = dt * in8[9] * t5 * t34 * t40;
  t362 = dt * in8[10] * t5 * t42 * t47;
  t363 = in8[3] * t5 * t34 * t35 * t40 * 0.5;
  t364 = in8[4] * t5 * t35 * t42 * t47 * 0.5;
  lagrangian_hessian_nz[0] = obj_factor * in4[0] * 2.0;
  lagrangian_hessian_nz[1] = obj_factor * in4[1] * 2.0;
  lagrangian_hessian_nz[2] = obj_factor * in4[2] * 2.0;
  lagrangian_hessian_nz[3] = (((((obj_factor * in4[3] * 2.0 - dt * in8[11] * t30
    * t33) - dt * in8[9] * t34 * t41) - dt * in8[10] * t42 * t48) - in8[5] * t30
    * t33 * t35 * 0.5) - in8[3] * t34 * t35 * t41 * 0.5) - in8[4] * t35 * t42 *
    t48 * 0.5;
  lagrangian_hessian_nz[4] = dt * t30 * t34 * t42 * t138 * (((((((((((((((in2[3]
    * in2[1] * t2 * t7 - in2[4] * in2[0] * t2 * t7) - in2[3] * in2[2] * t2 * t8)
    + in2[5] * in2[0] * t2 * t8) + in2[9] * in2[7] * t3 * t7) - in2[10] * in2[6]
    * t3 * t7) - in2[9] * in2[8] * t3 * t8) + in2[11] * in2[6] * t3 * t8) + in2
    [15] * in2[13] * t4 * t7) - in2[16] * in2[12] * t4 * t7) - in2[15] * in2[14]
    * t4 * t8) + in2[17] * in2[12] * t4 * t8) + in2[21] * in2[19] * t5 * t7) -
    in2[22] * in2[18] * t5 * t7) - in2[21] * in2[20] * t5 * t8) + in2[23] * in2
    [18] * t5 * t8) * 0.5;
  lagrangian_hessian_nz[5] = ((dt * in8[9] * t34 * t53 - dt * in8[10] * t42 *
    t56) + in8[3] * t34 * t35 * t53 * 0.5) - in8[4] * t35 * t42 * t56 * 0.5;
  lagrangian_hessian_nz[6] = ((((-dt * in8[9] * t34 * t59 - dt * in8[10] * t42 *
    t62) - in8[3] * t34 * t35 * t59 * 0.5) - in8[4] * t35 * t42 * t62 * 0.5) +
    dt * in8[11] * t2 * t6 * t30 * (t63 - in2[5] * t8)) + in8[5] * t2 * t6 * t30
    * t35 * (t63 - in2[5] * t8) * 0.5;
  lagrangian_hessian_nz[7] = ((((in2[3] * in8[3] * t2 * t34 * t35 * t40 * 0.5 +
    in2[3] * in8[4] * t2 * t35 * t42 * t47 * 0.5) + dt * in2[3] * in8[9] * t2 *
    t34 * t40) + dt * in2[3] * in8[10] * t2 * t42 * t47) - dt * in2[3] * in8[11]
    * t2 * t6 * t7 * t30) - in2[3] * in8[5] * t2 * t6 * t7 * t30 * t35 * 0.5;
  lagrangian_hessian_nz[8] = ((((in2[3] * in8[3] * t2 * t34 * t35 * t37 * 0.5 +
    in2[3] * in8[4] * t2 * t35 * t42 * t45 * 0.5) + dt * in2[3] * in8[9] * t2 *
    t34 * t37) + dt * in2[3] * in8[10] * t2 * t42 * t45) + dt * in2[3] * in8[11]
    * t2 * t6 * t8 * t30) + in2[3] * in8[5] * t2 * t6 * t8 * t30 * t35 * 0.5;
  lagrangian_hessian_nz[9] = ((((dt * in8[9] * t34 * t66 + dt * in8[10] * t42 *
    t69) + in8[3] * t34 * t35 * t66 * 0.5) + in8[4] * t35 * t42 * t69 * 0.5) -
    dt * in8[11] * t2 * t6 * t30 * t71) - in8[5] * t2 * t6 * t30 * t35 * t71 *
    0.5;
  lagrangian_hessian_nz[10] = ((((in8[3] * in2[0] * t2 * t34 * t35 * t40 * -0.5
    - in8[4] * in2[0] * t2 * t35 * t42 * t47 * 0.5) - dt * in8[9] * in2[0] * t2 *
    t34 * t40) - dt * in8[10] * in2[0] * t2 * t42 * t47) + dt * in8[11] * in2[0]
    * t2 * t6 * t7 * t30) + in8[5] * in2[0] * t2 * t6 * t7 * t30 * t35 * 0.5;
  lagrangian_hessian_nz[11] = ((((in8[3] * in2[0] * t2 * t34 * t35 * t37 * -0.5
    - in8[4] * in2[0] * t2 * t35 * t42 * t45 * 0.5) - dt * in8[9] * in2[0] * t2 *
    t34 * t37) - dt * in8[10] * in2[0] * t2 * t42 * t45) - dt * in8[11] * in2[0]
    * t2 * t6 * t8 * t30) - in8[5] * in2[0] * t2 * t6 * t8 * t30 * t35 * 0.5;
  lagrangian_hessian_nz[12] = ((((-dt * in8[9] * t34 * t74 - dt * in8[10] * t42 *
    t77) - in8[3] * t34 * t35 * t74 * 0.5) - in8[4] * t35 * t42 * t77 * 0.5) +
    dt * in8[11] * t3 * t6 * t30 * (t78 - in2[11] * t8)) + in8[5] * t3 * t6 *
    t30 * t35 * (t78 - in2[11] * t8) * 0.5;
  lagrangian_hessian_nz[13] = ((((in2[9] * in8[3] * t3 * t34 * t35 * t40 * 0.5 +
    in2[9] * in8[4] * t3 * t35 * t42 * t47 * 0.5) + dt * in2[9] * in8[9] * t3 *
    t34 * t40) + dt * in2[9] * in8[10] * t3 * t42 * t47) - dt * in2[9] * in8[11]
    * t3 * t6 * t7 * t30) - in2[9] * in8[5] * t3 * t6 * t7 * t30 * t35 * 0.5;
  lagrangian_hessian_nz[14] = ((((in2[9] * in8[3] * t3 * t34 * t35 * t37 * 0.5 +
    in2[9] * in8[4] * t3 * t35 * t42 * t45 * 0.5) + dt * in2[9] * in8[9] * t3 *
    t34 * t37) + dt * in2[9] * in8[10] * t3 * t42 * t45) + dt * in2[9] * in8[11]
    * t3 * t6 * t8 * t30) + in2[9] * in8[5] * t3 * t6 * t8 * t30 * t35 * 0.5;
  lagrangian_hessian_nz[15] = ((((dt * in8[9] * t34 * t81 + dt * in8[10] * t42 *
    t84) + in8[3] * t34 * t35 * t81 * 0.5) + in8[4] * t35 * t42 * t84 * 0.5) -
    dt * in8[11] * t3 * t6 * t30 * t86) - in8[5] * t3 * t6 * t30 * t35 * t86 *
    0.5;
  lagrangian_hessian_nz[16] = ((((in8[3] * in2[6] * t3 * t34 * t35 * t40 * -0.5
    - in8[4] * in2[6] * t3 * t35 * t42 * t47 * 0.5) - dt * in8[9] * in2[6] * t3 *
    t34 * t40) - dt * in8[10] * in2[6] * t3 * t42 * t47) + dt * in8[11] * in2[6]
    * t3 * t6 * t7 * t30) + in8[5] * in2[6] * t3 * t6 * t7 * t30 * t35 * 0.5;
  lagrangian_hessian_nz[17] = ((((in8[3] * in2[6] * t3 * t34 * t35 * t37 * -0.5
    - in8[4] * in2[6] * t3 * t35 * t42 * t45 * 0.5) - dt * in8[9] * in2[6] * t3 *
    t34 * t37) - dt * in8[10] * in2[6] * t3 * t42 * t45) - dt * in8[11] * in2[6]
    * t3 * t6 * t8 * t30) - in8[5] * in2[6] * t3 * t6 * t8 * t30 * t35 * 0.5;
  lagrangian_hessian_nz[18] = ((((-dt * in8[9] * t34 * t89 - dt * in8[10] * t42 *
    t92) - in8[3] * t34 * t35 * t89 * 0.5) - in8[4] * t35 * t42 * t92 * 0.5) +
    dt * in8[11] * t4 * t6 * t30 * (t93 - in2[17] * t8)) + in8[5] * t4 * t6 *
    t30 * t35 * (t93 - in2[17] * t8) * 0.5;
  lagrangian_hessian_nz[19] = ((((in2[15] * in8[3] * t4 * t34 * t35 * t40 * 0.5
    + in2[15] * in8[4] * t4 * t35 * t42 * t47 * 0.5) + dt * in2[15] * in8[9] *
    t4 * t34 * t40) + dt * in2[15] * in8[10] * t4 * t42 * t47) - dt * in2[15] *
    in8[11] * t4 * t6 * t7 * t30) - in2[15] * in8[5] * t4 * t6 * t7 * t30 * t35 *
    0.5;
  lagrangian_hessian_nz[20] = ((((in2[15] * in8[3] * t4 * t34 * t35 * t37 * 0.5
    + in2[15] * in8[4] * t4 * t35 * t42 * t45 * 0.5) + dt * in2[15] * in8[9] *
    t4 * t34 * t37) + dt * in2[15] * in8[10] * t4 * t42 * t45) + dt * in2[15] *
    in8[11] * t4 * t6 * t8 * t30) + in2[15] * in8[5] * t4 * t6 * t8 * t30 * t35 *
    0.5;
  lagrangian_hessian_nz[21] = ((((dt * in8[9] * t34 * t96 + dt * in8[10] * t42 *
    t99) + in8[3] * t34 * t35 * t96 * 0.5) + in8[4] * t35 * t42 * t99 * 0.5) -
    dt * in8[11] * t4 * t6 * t30 * t101) - in8[5] * t4 * t6 * t30 * t35 * t101 *
    0.5;
  lagrangian_hessian_nz[22] = ((((in8[3] * in2[12] * t4 * t34 * t35 * t40 * -0.5
    - in8[4] * in2[12] * t4 * t35 * t42 * t47 * 0.5) - dt * in8[9] * in2[12] *
    t4 * t34 * t40) - dt * in8[10] * in2[12] * t4 * t42 * t47) + dt * in8[11] *
    in2[12] * t4 * t6 * t7 * t30) + in8[5] * in2[12] * t4 * t6 * t7 * t30 * t35 *
    0.5;
  lagrangian_hessian_nz[23] = ((((in8[3] * in2[12] * t4 * t34 * t35 * t37 * -0.5
    - in8[4] * in2[12] * t4 * t35 * t42 * t45 * 0.5) - dt * in8[9] * in2[12] *
    t4 * t34 * t37) - dt * in8[10] * in2[12] * t4 * t42 * t45) - dt * in8[11] *
    in2[12] * t4 * t6 * t8 * t30) - in8[5] * in2[12] * t4 * t6 * t8 * t30 * t35 *
    0.5;
  lagrangian_hessian_nz[24] = ((((-dt * in8[9] * t34 * t104 - dt * in8[10] * t42
    * t107) - in8[3] * t34 * t35 * t104 * 0.5) - in8[4] * t35 * t42 * t107 * 0.5)
    + dt * in8[11] * t5 * t6 * t30 * (t108 - in2[23] * t8)) + in8[5] * t5 * t6 *
    t30 * t35 * (t108 - in2[23] * t8) * 0.5;
  lagrangian_hessian_nz[25] = ((((in2[21] * in8[3] * t5 * t34 * t35 * t40 * 0.5
    + in2[21] * in8[4] * t5 * t35 * t42 * t47 * 0.5) + dt * in2[21] * in8[9] *
    t5 * t34 * t40) + dt * in2[21] * in8[10] * t5 * t42 * t47) - dt * in2[21] *
    in8[11] * t5 * t6 * t7 * t30) - in2[21] * in8[5] * t5 * t6 * t7 * t30 * t35 *
    0.5;
  lagrangian_hessian_nz[26] = ((((in2[21] * in8[3] * t5 * t34 * t35 * t37 * 0.5
    + in2[21] * in8[4] * t5 * t35 * t42 * t45 * 0.5) + dt * in2[21] * in8[9] *
    t5 * t34 * t37) + dt * in2[21] * in8[10] * t5 * t42 * t45) + dt * in2[21] *
    in8[11] * t5 * t6 * t8 * t30) + in2[21] * in8[5] * t5 * t6 * t8 * t30 * t35 *
    0.5;
  lagrangian_hessian_nz[27] = ((((dt * in8[9] * t34 * t111 + dt * in8[10] * t42 *
    t114) + in8[3] * t34 * t35 * t111 * 0.5) + in8[4] * t35 * t42 * t114 * 0.5)
    - dt * in8[11] * t5 * t6 * t30 * t116) - in8[5] * t5 * t6 * t30 * t35 * t116
    * 0.5;
  lagrangian_hessian_nz[28] = ((((in8[3] * in2[18] * t5 * t34 * t35 * t40 * -0.5
    - in8[4] * in2[18] * t5 * t35 * t42 * t47 * 0.5) - dt * in8[9] * in2[18] *
    t5 * t34 * t40) - dt * in8[10] * in2[18] * t5 * t42 * t47) + dt * in8[11] *
    in2[18] * t5 * t6 * t7 * t30) + in8[5] * in2[18] * t5 * t6 * t7 * t30 * t35 *
    0.5;
  lagrangian_hessian_nz[29] = ((((in8[3] * in2[18] * t5 * t34 * t35 * t37 * -0.5
    - in8[4] * in2[18] * t5 * t35 * t42 * t45 * 0.5) - dt * in8[9] * in2[18] *
    t5 * t34 * t37) - dt * in8[10] * in2[18] * t5 * t42 * t45) - dt * in8[11] *
    in2[18] * t5 * t6 * t8 * t30) - in8[5] * in2[18] * t5 * t6 * t8 * t30 * t35 *
    0.5;
  lagrangian_hessian_nz[30] = (((((obj_factor * in4[4] * 2.0 + dt * in8[9] * t34
    * t128) - dt * in8[11] * t30 * t133) - dt * in8[10] * t42 * t131) + in8[3] *
    t34 * t35 * t128 * 0.5) - in8[5] * t30 * t35 * t133 * 0.5) - in8[4] * t35 *
    t42 * t131 * 0.5;
  lagrangian_hessian_nz[31] = dt * t34 * t42 * (((in9[1] * in8[9] * t14 * 2.0 +
    in9[0] * in8[10] * t15 * 2.0) + in9[1] * dt * in8[3] * t14) + in9[0] * dt *
    in8[4] * t15) * (((((((((((((((((((((((in2[4] * in2[2] * t2 * t16 - in2[5] *
    in2[1] * t2 * t16) + in2[10] * in2[8] * t3 * t16) - in2[11] * in2[7] * t3 *
    t16) + in2[16] * in2[14] * t4 * t16) - in2[17] * in2[13] * t4 * t16) + in2
    [22] * in2[20] * t5 * t16) - in2[23] * in2[19] * t5 * t16) + in2[3] * in2[1]
    * t2 * t6 * t8) + in2[3] * in2[2] * t2 * t6 * t7) - in2[4] * in2[0] * t2 *
    t6 * t8) - in2[5] * in2[0] * t2 * t6 * t7) + in2[9] * in2[7] * t3 * t6 * t8)
    + in2[9] * in2[8] * t3 * t6 * t7) - in2[10] * in2[6] * t3 * t6 * t8) - in2
    [11] * in2[6] * t3 * t6 * t7) + in2[15] * in2[13] * t4 * t6 * t8) + in2[15] *
    in2[14] * t4 * t6 * t7) - in2[16] * in2[12] * t4 * t6 * t8) - in2[17] * in2
    [12] * t4 * t6 * t7) + in2[21] * in2[19] * t5 * t6 * t8) + in2[21] * in2[20]
                       * t5 * t6 * t7) - in2[22] * in2[18] * t5 * t6 * t8) -
                     in2[23] * in2[18] * t5 * t6 * t7) * 0.5;
  lagrangian_hessian_nz[32] = dt * t2 * t30 * t34 * t42 * t138 * (in2[4] * t8 +
    in2[5] * t7) * 0.5;
  lagrangian_hessian_nz[33] = ((((-dt * in8[11] * t2 * t30 * t141 - in8[5] * t2 *
    t30 * t35 * t141 * 0.5) + dt * in8[9] * t2 * t15 * t34 * t143) - dt * in8[10]
    * t2 * t14 * t42 * t143) + in8[3] * t2 * t15 * t34 * t35 * t143 * 0.5) -
    in8[4] * t2 * t14 * t35 * t42 * t143 * 0.5;
  lagrangian_hessian_nz[34] = ((((dt * in8[11] * t2 * t30 * t146 + in8[5] * t2 *
    t30 * t35 * t146 * 0.5) - dt * in8[9] * t2 * t15 * t34 * t149) + dt * in8[10]
    * t2 * t14 * t42 * t149) - in8[3] * t2 * t15 * t34 * t35 * t149 * 0.5) +
    in8[4] * t2 * t14 * t35 * t42 * t149 * 0.5;
  lagrangian_hessian_nz[35] = dt * t2 * t30 * t34 * t42 * t138 * (in2[1] * t8 +
    in2[2] * t7) * -0.5;
  lagrangian_hessian_nz[36] = ((((dt * in8[11] * t2 * t30 * t154 + in8[5] * t2 *
    t30 * t35 * t154 * 0.5) - dt * in8[9] * t2 * t15 * t34 * t156) + dt * in8[10]
    * t2 * t14 * t42 * t156) - in8[3] * t2 * t15 * t34 * t35 * t156 * 0.5) +
    in8[4] * t2 * t14 * t35 * t42 * t156 * 0.5;
  lagrangian_hessian_nz[37] = ((((-dt * in8[11] * t2 * t30 * t159 - in8[5] * t2 *
    t30 * t35 * t159 * 0.5) + dt * in8[9] * t2 * t15 * t34 * t162) - dt * in8[10]
    * t2 * t14 * t42 * t162) + in8[3] * t2 * t15 * t34 * t35 * t162 * 0.5) -
    in8[4] * t2 * t14 * t35 * t42 * t162 * 0.5;
  lagrangian_hessian_nz[38] = dt * t3 * t30 * t34 * t42 * t138 * (in2[10] * t8 +
    in2[11] * t7) * 0.5;
  lagrangian_hessian_nz[39] = ((((-dt * in8[11] * t3 * t30 * t165 - in8[5] * t3 *
    t30 * t35 * t165 * 0.5) + dt * in8[9] * t3 * t15 * t34 * t167) - dt * in8[10]
    * t3 * t14 * t42 * t167) + in8[3] * t3 * t15 * t34 * t35 * t167 * 0.5) -
    in8[4] * t3 * t14 * t35 * t42 * t167 * 0.5;
  lagrangian_hessian_nz[40] = ((((dt * in8[11] * t3 * t30 * t170 + in8[5] * t3 *
    t30 * t35 * t170 * 0.5) - dt * in8[9] * t3 * t15 * t34 * t173) + dt * in8[10]
    * t3 * t14 * t42 * t173) - in8[3] * t3 * t15 * t34 * t35 * t173 * 0.5) +
    in8[4] * t3 * t14 * t35 * t42 * t173 * 0.5;
  lagrangian_hessian_nz[41] = dt * t3 * t30 * t34 * t42 * t138 * (in2[7] * t8 +
    in2[8] * t7) * -0.5;
  lagrangian_hessian_nz[42] = ((((dt * in8[11] * t3 * t30 * t176 + in8[5] * t3 *
    t30 * t35 * t176 * 0.5) - dt * in8[9] * t3 * t15 * t34 * t178) + dt * in8[10]
    * t3 * t14 * t42 * t178) - in8[3] * t3 * t15 * t34 * t35 * t178 * 0.5) +
    in8[4] * t3 * t14 * t35 * t42 * t178 * 0.5;
  lagrangian_hessian_nz[43] = ((((-dt * in8[11] * t3 * t30 * t181 - in8[5] * t3 *
    t30 * t35 * t181 * 0.5) + dt * in8[9] * t3 * t15 * t34 * t184) - dt * in8[10]
    * t3 * t14 * t42 * t184) + in8[3] * t3 * t15 * t34 * t35 * t184 * 0.5) -
    in8[4] * t3 * t14 * t35 * t42 * t184 * 0.5;
  lagrangian_hessian_nz[44] = dt * t4 * t30 * t34 * t42 * t138 * (in2[16] * t8 +
    in2[17] * t7) * 0.5;
  lagrangian_hessian_nz[45] = ((((-dt * in8[11] * t4 * t30 * t187 - in8[5] * t4 *
    t30 * t35 * t187 * 0.5) + dt * in8[9] * t4 * t15 * t34 * t189) - dt * in8[10]
    * t4 * t14 * t42 * t189) + in8[3] * t4 * t15 * t34 * t35 * t189 * 0.5) -
    in8[4] * t4 * t14 * t35 * t42 * t189 * 0.5;
  lagrangian_hessian_nz[46] = ((((dt * in8[11] * t4 * t30 * t192 + in8[5] * t4 *
    t30 * t35 * t192 * 0.5) - dt * in8[9] * t4 * t15 * t34 * t195) + dt * in8[10]
    * t4 * t14 * t42 * t195) - in8[3] * t4 * t15 * t34 * t35 * t195 * 0.5) +
    in8[4] * t4 * t14 * t35 * t42 * t195 * 0.5;
  lagrangian_hessian_nz[47] = dt * t4 * t30 * t34 * t42 * t138 * (in2[13] * t8 +
    in2[14] * t7) * -0.5;
  lagrangian_hessian_nz[48] = ((((dt * in8[11] * t4 * t30 * t198 + in8[5] * t4 *
    t30 * t35 * t198 * 0.5) - dt * in8[9] * t4 * t15 * t34 * t200) + dt * in8[10]
    * t4 * t14 * t42 * t200) - in8[3] * t4 * t15 * t34 * t35 * t200 * 0.5) +
    in8[4] * t4 * t14 * t35 * t42 * t200 * 0.5;
  lagrangian_hessian_nz[49] = ((((-dt * in8[11] * t4 * t30 * t203 - in8[5] * t4 *
    t30 * t35 * t203 * 0.5) + dt * in8[9] * t4 * t15 * t34 * t206) - dt * in8[10]
    * t4 * t14 * t42 * t206) + in8[3] * t4 * t15 * t34 * t35 * t206 * 0.5) -
    in8[4] * t4 * t14 * t35 * t42 * t206 * 0.5;
  lagrangian_hessian_nz[50] = dt * t5 * t30 * t34 * t42 * t138 * (in2[22] * t8 +
    in2[23] * t7) * 0.5;
  lagrangian_hessian_nz[51] = ((((-dt * in8[11] * t5 * t30 * t209 - in8[5] * t5 *
    t30 * t35 * t209 * 0.5) + dt * in8[9] * t5 * t15 * t34 * t211) - dt * in8[10]
    * t5 * t14 * t42 * t211) + in8[3] * t5 * t15 * t34 * t35 * t211 * 0.5) -
    in8[4] * t5 * t14 * t35 * t42 * t211 * 0.5;
  lagrangian_hessian_nz[52] = ((((dt * in8[11] * t5 * t30 * t214 + in8[5] * t5 *
    t30 * t35 * t214 * 0.5) - dt * in8[9] * t5 * t15 * t34 * t217) + dt * in8[10]
    * t5 * t14 * t42 * t217) - in8[3] * t5 * t15 * t34 * t35 * t217 * 0.5) +
    in8[4] * t5 * t14 * t35 * t42 * t217 * 0.5;
  lagrangian_hessian_nz[53] = dt * t5 * t30 * t34 * t42 * t138 * (in2[19] * t8 +
    in2[20] * t7) * -0.5;
  lagrangian_hessian_nz[54] = ((((dt * in8[11] * t5 * t30 * t220 + in8[5] * t5 *
    t30 * t35 * t220 * 0.5) - dt * in8[9] * t5 * t15 * t34 * t222) + dt * in8[10]
    * t5 * t14 * t42 * t222) - in8[3] * t5 * t15 * t34 * t35 * t222 * 0.5) +
    in8[4] * t5 * t14 * t35 * t42 * t222 * 0.5;
  lagrangian_hessian_nz[55] = ((((-dt * in8[11] * t5 * t30 * t225 - in8[5] * t5 *
    t30 * t35 * t225 * 0.5) + dt * in8[9] * t5 * t15 * t34 * t228) - dt * in8[10]
    * t5 * t14 * t42 * t228) + in8[3] * t5 * t15 * t34 * t35 * t228 * 0.5) -
    in8[4] * t5 * t14 * t35 * t42 * t228 * 0.5;
  lagrangian_hessian_nz[56] = (((obj_factor * in4[5] * 2.0 - dt * in8[9] * t34 *
    t235) + dt * in8[10] * t42 * t13) - in8[3] * t34 * t35 * t235 * 0.5) + in8[4]
    * t35 * t42 * t13 * 0.5;
  lagrangian_hessian_nz[57] = ((-dt * in8[9] * t34 * t21 + dt * in8[10] * t42 *
    t31) - in8[3] * t34 * t35 * t21 * 0.5) + in8[4] * t35 * t42 * t31 * 0.5;
  lagrangian_hessian_nz[58] = ((dt * in8[9] * t34 * t32 - dt * in8[10] * t42 *
    t121) + in8[3] * t34 * t35 * t32 * 0.5) - in8[4] * t35 * t42 * t121 * 0.5;
  lagrangian_hessian_nz[59] = ((-dt * in8[9] * t34 * t229 + dt * in8[10] * t42 *
    t230) - in8[3] * t34 * t35 * t229 * 0.5) + in8[4] * t35 * t42 * t230 * 0.5;
  lagrangian_hessian_nz[60] = ((dt * in8[9] * t34 * t231 - dt * in8[10] * t42 *
    t232) + in8[3] * t34 * t35 * t231 * 0.5) - in8[4] * t35 * t42 * t232 * 0.5;
  lagrangian_hessian_nz[61] = ((-dt * in8[9] * t34 * t234 + dt * in8[10] * t42 *
    t233) - in8[3] * t34 * t35 * t234 * 0.5) + in8[4] * t35 * t42 * t233 * 0.5;
  lagrangian_hessian_nz[62] = ((dt * in8[9] * t34 * t264 - dt * in8[10] * t42 *
    t261) + in8[3] * t34 * t35 * t264 * 0.5) - in8[4] * t35 * t42 * t261 * 0.5;
  lagrangian_hessian_nz[63] = ((-dt * in8[9] * t34 * t266 + dt * in8[10] * t42 *
    t268) - in8[3] * t34 * t35 * t266 * 0.5) + in8[4] * t35 * t42 * t268 * 0.5;
  lagrangian_hessian_nz[64] = ((dt * in8[9] * t34 * t271 - dt * in8[10] * t42 *
    t273) + in8[3] * t34 * t35 * t271 * 0.5) - in8[4] * t35 * t42 * t273 * 0.5;
  lagrangian_hessian_nz[65] = ((-dt * in8[9] * t34 * t276 + dt * in8[10] * t42 *
    t278) - in8[3] * t34 * t35 * t276 * 0.5) + in8[4] * t35 * t42 * t278 * 0.5;
  lagrangian_hessian_nz[66] = ((dt * in8[9] * t34 * t280 - dt * in8[10] * t42 *
    t282) + in8[3] * t34 * t35 * t280 * 0.5) - in8[4] * t35 * t42 * t282 * 0.5;
  lagrangian_hessian_nz[67] = ((-dt * in8[9] * t34 * t287 + dt * in8[10] * t42 *
    t284) - in8[3] * t34 * t35 * t287 * 0.5) + in8[4] * t35 * t42 * t284 * 0.5;
  lagrangian_hessian_nz[68] = ((dt * in8[9] * t34 * t292 - dt * in8[10] * t42 *
    t289) + in8[3] * t34 * t35 * t292 * 0.5) - in8[4] * t35 * t42 * t289 * 0.5;
  lagrangian_hessian_nz[69] = ((-dt * in8[9] * t34 * t294 + dt * in8[10] * t42 *
    t296) - in8[3] * t34 * t35 * t294 * 0.5) + in8[4] * t35 * t42 * t296 * 0.5;
  lagrangian_hessian_nz[70] = ((dt * in8[9] * t34 * t299 - dt * in8[10] * t42 *
    t301) + in8[3] * t34 * t35 * t299 * 0.5) - in8[4] * t35 * t42 * t301 * 0.5;
  lagrangian_hessian_nz[71] = ((-dt * in8[9] * t34 * t304 + dt * in8[10] * t42 *
    t306) - in8[3] * t34 * t35 * t304 * 0.5) + in8[4] * t35 * t42 * t306 * 0.5;
  lagrangian_hessian_nz[72] = ((dt * in8[9] * t34 * t308 - dt * in8[10] * t42 *
    t310) + in8[3] * t34 * t35 * t308 * 0.5) - in8[4] * t35 * t42 * t310 * 0.5;
  lagrangian_hessian_nz[73] = ((-dt * in8[9] * t34 * t315 + dt * in8[10] * t42 *
    t312) - in8[3] * t34 * t35 * t315 * 0.5) + in8[4] * t35 * t42 * t312 * 0.5;
  lagrangian_hessian_nz[74] = ((dt * in8[9] * t34 * t320 - dt * in8[10] * t42 *
    t317) + in8[3] * t34 * t35 * t320 * 0.5) - in8[4] * t35 * t42 * t317 * 0.5;
  lagrangian_hessian_nz[75] = ((-dt * in8[9] * t34 * t322 + dt * in8[10] * t42 *
    t324) - in8[3] * t34 * t35 * t322 * 0.5) + in8[4] * t35 * t42 * t324 * 0.5;
  lagrangian_hessian_nz[76] = ((dt * in8[9] * t34 * t327 - dt * in8[10] * t42 *
    t329) + in8[3] * t34 * t35 * t327 * 0.5) - in8[4] * t35 * t42 * t329 * 0.5;
  lagrangian_hessian_nz[77] = ((-dt * in8[9] * t34 * t332 + dt * in8[10] * t42 *
    t334) - in8[3] * t34 * t35 * t332 * 0.5) + in8[4] * t35 * t42 * t334 * 0.5;
  lagrangian_hessian_nz[78] = ((dt * in8[9] * t34 * t336 - dt * in8[10] * t42 *
    t338) + in8[3] * t34 * t35 * t336 * 0.5) - in8[4] * t35 * t42 * t338 * 0.5;
  lagrangian_hessian_nz[79] = ((-dt * in8[9] * t34 * t343 + dt * in8[10] * t42 *
    t340) - in8[3] * t34 * t35 * t343 * 0.5) + in8[4] * t35 * t42 * t340 * 0.5;
  lagrangian_hessian_nz[80] = ((dt * in8[9] * t34 * t348 - dt * in8[10] * t42 *
    t345) + in8[3] * t34 * t35 * t348 * 0.5) - in8[4] * t35 * t42 * t345 * 0.5;
  lagrangian_hessian_nz[81] = obj_factor * in4[6] * 2.0;
  lagrangian_hessian_nz[82] = obj_factor * in4[7] * 2.0;
  lagrangian_hessian_nz[83] = obj_factor * in4[8] * 2.0;
  lagrangian_hessian_nz[84] = obj_factor * in4[9] * 2.0;
  lagrangian_hessian_nz[85] = obj_factor * in4[10] * 2.0;
  lagrangian_hessian_nz[86] = obj_factor * in4[11] * 2.0;
  lagrangian_hessian_nz[87] = obj_factor * in5[0] * 2.0;
  lagrangian_hessian_nz[88] = ((((-dt * in8[9] * t2 * t34 * t37 - dt * in8[10] *
    t2 * t42 * t45) - in8[3] * t2 * t34 * t35 * t37 * 0.5) - in8[4] * t2 * t35 *
    t42 * t45 * 0.5) - dt * in8[11] * t2 * t6 * t8 * t30) - in8[5] * t2 * t6 *
    t8 * t30 * t35 * 0.5;
  lagrangian_hessian_nz[89] = ((((t349 + t350) + t351) + t352) - dt * in8[11] *
    t2 * t6 * t7 * t30) - in8[5] * t2 * t6 * t7 * t30 * t35 * 0.5;
  lagrangian_hessian_nz[90] = obj_factor * in5[1] * 2.0;
  lagrangian_hessian_nz[91] = ((((dt * in8[9] * t2 * t34 * t37 + dt * in8[10] *
    t2 * t42 * t45) + in8[3] * t2 * t34 * t35 * t37 * 0.5) + in8[4] * t2 * t35 *
    t42 * t45 * 0.5) + dt * in8[11] * t2 * t6 * t8 * t30) + in8[5] * t2 * t6 *
    t8 * t30 * t35 * 0.5;
  lagrangian_hessian_nz[92] = dt * t2 * t30 * t34 * t42 * t138 * -0.5;
  lagrangian_hessian_nz[93] = obj_factor * in5[2] * 2.0;
  lagrangian_hessian_nz[94] = ((((-t349 - t350) - t351) - t352) + dt * in8[11] *
    t2 * t6 * t7 * t30) + in8[5] * t2 * t6 * t7 * t30 * t35 * 0.5;
  lagrangian_hessian_nz[95] = dt * t2 * t30 * t34 * t42 * t138 * 0.5;
  lagrangian_hessian_nz[96] = obj_factor * in5[3] * 2.0;
  lagrangian_hessian_nz[97] = obj_factor * in5[4] * 2.0;
  lagrangian_hessian_nz[98] = obj_factor * in5[5] * 2.0;
  lagrangian_hessian_nz[99] = obj_factor * in5[6] * 2.0;
  lagrangian_hessian_nz[100] = ((((-dt * in8[9] * t3 * t34 * t37 - dt * in8[10] *
    t3 * t42 * t45) - in8[3] * t3 * t34 * t35 * t37 * 0.5) - in8[4] * t3 * t35 *
    t42 * t45 * 0.5) - dt * in8[11] * t3 * t6 * t8 * t30) - in8[5] * t3 * t6 *
    t8 * t30 * t35 * 0.5;
  lagrangian_hessian_nz[101] = ((((t353 + t354) + t355) + t356) - dt * in8[11] *
    t3 * t6 * t7 * t30) - in8[5] * t3 * t6 * t7 * t30 * t35 * 0.5;
  lagrangian_hessian_nz[102] = obj_factor * in5[7] * 2.0;
  lagrangian_hessian_nz[103] = ((((dt * in8[9] * t3 * t34 * t37 + dt * in8[10] *
    t3 * t42 * t45) + in8[3] * t3 * t34 * t35 * t37 * 0.5) + in8[4] * t3 * t35 *
    t42 * t45 * 0.5) + dt * in8[11] * t3 * t6 * t8 * t30) + in8[5] * t3 * t6 *
    t8 * t30 * t35 * 0.5;
  lagrangian_hessian_nz[104] = dt * t3 * t30 * t34 * t42 * t138 * -0.5;
  lagrangian_hessian_nz[105] = obj_factor * in5[8] * 2.0;
  lagrangian_hessian_nz[106] = ((((-t353 - t354) - t355) - t356) + dt * in8[11] *
    t3 * t6 * t7 * t30) + in8[5] * t3 * t6 * t7 * t30 * t35 * 0.5;
  lagrangian_hessian_nz[107] = dt * t3 * t30 * t34 * t42 * t138 * 0.5;
  lagrangian_hessian_nz[108] = obj_factor * in5[9] * 2.0;
  lagrangian_hessian_nz[109] = obj_factor * in5[10] * 2.0;
  lagrangian_hessian_nz[110] = obj_factor * in5[11] * 2.0;
  lagrangian_hessian_nz[111] = obj_factor * in5[12] * 2.0;
  lagrangian_hessian_nz[112] = ((((-dt * in8[9] * t4 * t34 * t37 - dt * in8[10] *
    t4 * t42 * t45) - in8[3] * t4 * t34 * t35 * t37 * 0.5) - in8[4] * t4 * t35 *
    t42 * t45 * 0.5) - dt * in8[11] * t4 * t6 * t8 * t30) - in8[5] * t4 * t6 *
    t8 * t30 * t35 * 0.5;
  lagrangian_hessian_nz[113] = ((((t357 + t358) + t359) + t360) - dt * in8[11] *
    t4 * t6 * t7 * t30) - in8[5] * t4 * t6 * t7 * t30 * t35 * 0.5;
  lagrangian_hessian_nz[114] = obj_factor * in5[13] * 2.0;
  lagrangian_hessian_nz[115] = ((((dt * in8[9] * t4 * t34 * t37 + dt * in8[10] *
    t4 * t42 * t45) + in8[3] * t4 * t34 * t35 * t37 * 0.5) + in8[4] * t4 * t35 *
    t42 * t45 * 0.5) + dt * in8[11] * t4 * t6 * t8 * t30) + in8[5] * t4 * t6 *
    t8 * t30 * t35 * 0.5;
  lagrangian_hessian_nz[116] = dt * t4 * t30 * t34 * t42 * t138 * -0.5;
  lagrangian_hessian_nz[117] = obj_factor * in5[14] * 2.0;
  lagrangian_hessian_nz[118] = ((((-t357 - t358) - t359) - t360) + dt * in8[11] *
    t4 * t6 * t7 * t30) + in8[5] * t4 * t6 * t7 * t30 * t35 * 0.5;
  lagrangian_hessian_nz[119] = dt * t4 * t30 * t34 * t42 * t138 * 0.5;
  lagrangian_hessian_nz[120] = obj_factor * in5[15] * 2.0;
  lagrangian_hessian_nz[121] = obj_factor * in5[16] * 2.0;
  lagrangian_hessian_nz[122] = obj_factor * in5[17] * 2.0;
  lagrangian_hessian_nz[123] = obj_factor * in5[18] * 2.0;
  lagrangian_hessian_nz[124] = ((((-dt * in8[9] * t5 * t34 * t37 - dt * in8[10] *
    t5 * t42 * t45) - in8[3] * t5 * t34 * t35 * t37 * 0.5) - in8[4] * t5 * t35 *
    t42 * t45 * 0.5) - dt * in8[11] * t5 * t6 * t8 * t30) - in8[5] * t5 * t6 *
    t8 * t30 * t35 * 0.5;
  lagrangian_hessian_nz[125] = ((((t361 + t362) + t363) + t364) - dt * in8[11] *
    t5 * t6 * t7 * t30) - in8[5] * t5 * t6 * t7 * t30 * t35 * 0.5;
  lagrangian_hessian_nz[126] = obj_factor * in5[19] * 2.0;
  lagrangian_hessian_nz[127] = ((((dt * in8[9] * t5 * t34 * t37 + dt * in8[10] *
    t5 * t42 * t45) + in8[3] * t5 * t34 * t35 * t37 * 0.5) + in8[4] * t5 * t35 *
    t42 * t45 * 0.5) + dt * in8[11] * t5 * t6 * t8 * t30) + in8[5] * t5 * t6 *
    t8 * t30 * t35 * 0.5;
  lagrangian_hessian_nz[128] = dt * t5 * t30 * t34 * t42 * t138 * -0.5;
  lagrangian_hessian_nz[129] = obj_factor * in5[20] * 2.0;
  lagrangian_hessian_nz[130] = ((((-t361 - t362) - t363) - t364) + dt * in8[11] *
    t5 * t6 * t7 * t30) + in8[5] * t5 * t6 * t7 * t30 * t35 * 0.5;
  lagrangian_hessian_nz[131] = dt * t5 * t30 * t34 * t42 * t138 * 0.5;
  lagrangian_hessian_nz[132] = obj_factor * in5[21] * 2.0;
  lagrangian_hessian_nz[133] = obj_factor * in5[22] * 2.0;
  lagrangian_hessian_nz[134] = obj_factor * in5[23] * 2.0;
}

//
// File trailer for RPCLagrangianHessian.cpp
//
// [EOF]
//
