function A = A_passive(in1,in2)
%A_PASSIVE
%    A = A_PASSIVE(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    11-Jul-2024 07:21:02

M = in2(1,:);
l = in2(3,:);
m = in2(2,:);
phi = in1(2,:);
t2 = cos(phi);
t3 = l.^2;
t4 = t2.*2.0;
t5 = t4-2.0;
t6 = (m.*t3.*t5)./2.0;
A = reshape([M.*t3-(m.*t3.*(t2.*4.0-4.0))./2.0,t6,t6,m.*t3],[2,2]);
