function E = energy_passive(in1,in2)
%ENERGY_PASSIVE
%    E = ENERGY_PASSIVE(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    11-Jul-2024 07:21:01

M = in2(1,:);
dphi = in1(4,:);
dth = in1(3,:);
g = in2(4,:);
l = in2(3,:);
m = in2(2,:);
phi = in1(2,:);
th = in1(1,:);
t2 = cos(phi);
t3 = cos(th);
t4 = dth.^2;
t5 = l.^2;
E = (m.*t5.*(t4.*2.0-dphi.*dth.*2.0-t2.*t4.*2.0+dphi.^2+dphi.*dth.*t2.*2.0))./2.0+(M.*t4.*t5)./2.0+g.*m.*(l.*t3-l.*cos(phi-th))+M.*g.*l.*t3;
