function gravity = grav_passive(in1,in2)
%GRAV_PASSIVE
%    GRAVITY = GRAV_PASSIVE(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    11-Jul-2024 07:21:02

M = in2(1,:);
g = in2(4,:);
l = in2(3,:);
m = in2(2,:);
phi = in1(2,:);
th = in1(1,:);
t2 = sin(th);
t3 = -th;
t4 = phi+t3;
t5 = sin(t4);
gravity = [-g.*m.*(l.*t2+l.*t5)-M.*g.*l.*t2;g.*l.*m.*t5];
