function keypoints_J = J_passive(in1,in2)
%J_PASSIVE
%    KEYPOINTS_J = J_PASSIVE(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    11-Jul-2024 07:21:02

l = in2(3,:);
phi = in1(2,:);
th = in1(1,:);
t2 = cos(th);
t3 = sin(th);
t6 = -th;
t4 = l.*t2;
t5 = l.*t3;
t8 = phi+t6;
t7 = -t4;
t9 = -t5;
t10 = cos(t8);
t11 = sin(t8);
t12 = l.*t10;
t13 = l.*t11;
keypoints_J = reshape([t7,t9,t7+t12,t9-t13,0.0,0.0,-t12,t13],[4,2]);
