function keypoints_Jdot = Jdot_passive(in1,in2)
%JDOT_PASSIVE
%    KEYPOINTS_JDOT = JDOT_PASSIVE(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    11-Jul-2024 07:21:02

dphi = in1(4,:);
dth = in1(3,:);
l = in2(3,:);
phi = in1(2,:);
th = in1(1,:);
t2 = cos(th);
t3 = sin(th);
t4 = -th;
t5 = phi+t4;
t6 = cos(t5);
t7 = sin(t5);
t8 = dphi.*l.*t6;
t9 = dphi.*l.*t7;
keypoints_Jdot = reshape([dth.*l.*t3,-dth.*l.*t2,-t9+dth.*(l.*t3+l.*t7),-t8-dth.*(l.*t2-l.*t6),0.0,0.0,t9-dth.*l.*t7,t8-dth.*l.*t6],[4,2]);
