function keypoints = keypoints_passive(in1,in2)
%KEYPOINTS_PASSIVE
%    KEYPOINTS = KEYPOINTS_PASSIVE(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    11-Jul-2024 07:21:02

l = in2(3,:);
phi = in1(2,:);
th = in1(1,:);
t2 = cos(th);
t3 = sin(th);
t6 = -th;
t4 = l.*t2;
t5 = l.*t3;
t7 = phi+t6;
t8 = -t5;
keypoints = reshape([t8,t4,t8-l.*sin(t7),t4-l.*cos(t7)],[2,2]);
