function keypoints_vel = keypoints_vel_passive(in1,in2)
%KEYPOINTS_VEL_PASSIVE
%    KEYPOINTS_VEL = KEYPOINTS_VEL_PASSIVE(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    11-Jul-2024 07:21:02

dphi = in1(4,:);
dth = in1(3,:);
l = in2(3,:);
phi = in1(2,:);
th = in1(1,:);
t2 = cos(th);
t3 = sin(th);
t4 = -th;
t5 = phi+t4;
t6 = cos(t5);
t7 = sin(t5);
keypoints_vel = reshape([-dth.*l.*t2,-dth.*l.*t3,-dth.*(l.*t2-l.*t6)-dphi.*l.*t6,-dth.*(l.*t3+l.*t7)+dphi.*l.*t7],[2,2]);
