function gravity = grav_biped(in1)
%GRAV_BIPED
%    GRAVITY = GRAV_BIPED(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    12-Jul-2024 15:34:03

q_ankle_l = in1(10,:);
q_ankle_r = in1(6,:);
q_hip_l = in1(8,:);
q_hip_r = in1(4,:);
q_knee_l = in1(9,:);
q_knee_r = in1(5,:);
q_toe_l = in1(11,:);
q_toe_r = in1(7,:);
th = in1(3,:);
t2 = q_hip_l+th;
t3 = q_hip_r+th;
t14 = atan(8.5e+1./2.4e+1);
t15 = 8.832326986700617e+1;
t4 = q_knee_l+t2;
t5 = q_knee_r+t3;
t6 = sin(t2);
t7 = sin(t3);
t16 = -t14;
t8 = sin(t4);
t9 = sin(t5);
t10 = q_ankle_l+q_toe_l+t4;
t11 = q_ankle_r+q_toe_r+t5;
t17 = q_ankle_l+t4+t16;
t18 = q_ankle_r+t5+t16;
t23 = t6.*1.112454e+1;
t24 = t7.*1.112454e+1;
t12 = sin(t10);
t13 = sin(t11);
t19 = cos(t17);
t20 = cos(t18);
t21 = t8.*3.84552;
t22 = t9.*3.84552;
t25 = t12.*9.81e-3;
t26 = t13.*9.81e-3;
t27 = t15.*t19.*1.962e-3;
t28 = t15.*t20.*1.962e-3;
gravity = [0.0;1.92276e+2;t21+t22+t23+t24+t25+t26+t27+t28-sin(th).*(9.81e+2./5.0e+1);t22+t24+t26+t28;t22+t26+t28;t26+t28;t26;t21+t23+t25+t27;t21+t25+t27;t25+t27;t25];
