function coriolis = coriolis_arm(in1)
%CORIOLIS_ARM
%    CORIOLIS = CORIOLIS_ARM(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    09-Feb-2024 09:57:03

dq1 = in1(4,:);
dq2 = in1(5,:);
dq3 = in1(6,:);
q2 = in1(2,:);
q3 = in1(3,:);
t2 = sin(q2);
t3 = sin(q3);
t4 = q2+q3;
t5 = dq1.^2;
t6 = dq2.^2;
t7 = dq3.^2;
t8 = sin(t4);
t9 = dq1.*dq3.*t3.*(2.7e+1./2.5e+2);
t10 = dq2.*dq3.*t3.*(2.7e+1./2.5e+2);
t11 = t3.*t7.*(2.7e+1./5.0e+2);
t12 = -t9;
t13 = -t10;
t14 = -t11;
t15 = t5.*t8.*5.04e-2;
coriolis = [t12+t13+t14-t2.*t6.*(6.3e+1./2.5e+2)-t6.*t8.*5.04e-2-t7.*t8.*5.04e-2-dq1.*dq2.*t2.*(6.3e+1./1.25e+2)-dq1.*dq2.*t8.*(6.3e+1./6.25e+2)-dq1.*dq3.*t8.*(6.3e+1./6.25e+2)-dq2.*dq3.*t8.*(6.3e+1./6.25e+2);t12+t13+t14+t15+t2.*t5.*(6.3e+1./2.5e+2);t15+t3.*t5.*(2.7e+1./5.0e+2)+t3.*t6.*(2.7e+1./5.0e+2)+dq1.*dq2.*t3.*(2.7e+1./2.5e+2)];
