function gravity = grav_arm(in1)
%GRAV_ARM
%    GRAVITY = GRAV_ARM(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    09-Feb-2024 09:57:03

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
t2 = q1+q2;
t3 = cos(t2);
t4 = q3+t2;
t5 = cos(t4);
t6 = t3.*8.829;
t7 = t5.*1.7658;
gravity = [t6+t7+cos(q1).*2.26611e+1;t6+t7;t7];
