function keypoints = keypoints_arm(in1)
%KEYPOINTS_ARM
%    KEYPOINTS = KEYPOINTS_ARM(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    09-Feb-2024 09:57:03

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
t2 = cos(q1);
t3 = sin(q1);
t4 = q1+q2;
t5 = cos(t4);
t6 = q3+t4;
t7 = sin(t4);
t8 = t2.*(7.0./2.5e+1);
t9 = t3.*(7.0./2.5e+1);
t10 = t5.*(3.0./1.0e+1);
t11 = t7.*(3.0./1.0e+1);
keypoints = reshape([t8,t9,t8+t10,t9+t11,t8+t10+cos(t6).*(9.0./5.0e+1),t9+t11+sin(t6).*(9.0./5.0e+1)],[2,3]);
