function keypoints_vel = keypoints_vel_arm(in1)
%KEYPOINTS_VEL_ARM
%    KEYPOINTS_VEL = KEYPOINTS_VEL_ARM(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    09-Feb-2024 09:57:03

dq1 = in1(4,:);
dq2 = in1(5,:);
dq3 = in1(6,:);
q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
t2 = cos(q1);
t3 = sin(q1);
t4 = q1+q2;
t5 = cos(t4);
t6 = q3+t4;
t7 = sin(t4);
t10 = t2.*(7.0./2.5e+1);
t11 = t3.*(7.0./2.5e+1);
t8 = cos(t6);
t9 = sin(t6);
t12 = t5.*(3.0./1.0e+1);
t13 = t7.*(3.0./1.0e+1);
t14 = t8.*(9.0./5.0e+1);
t15 = t9.*(9.0./5.0e+1);
keypoints_vel = reshape([dq1.*t3.*(-7.0./2.5e+1),dq1.*t10,-dq1.*(t11+t13)-dq2.*t7.*(3.0./1.0e+1),dq1.*(t10+t12)+dq2.*t12,-dq2.*(t13+t15)-dq3.*t9.*(9.0./5.0e+1)-dq1.*(t11+t13+t15),dq2.*(t12+t14)+dq3.*t14+dq1.*(t10+t12+t14)],[2,3]);
