//
//  Academic License - for use in teaching, academic research, and meeting
//  course requirements at degree granting institutions only.  Not for
//  government, commercial, or other organizational use.
//
//  matrixFunction.cpp
//
//  Code generation for function 'matrixFunction'
//


// Include files
#include "matrixFunction.h"

// Function Definitions
void matrixFunction(const Vector<double, 2,1> & in1, Eigen::Matrix<double, 2,2> & A)
{
  double t2;

  // MATRIXFUNCTION
  //     A = MATRIXFUNCTION(IN1)
  //     This function was generated by the Symbolic Math Toolbox version 8.6.
  //     05-Feb-2024 12:41:46
  t2 = in1[0] * in1[0];
  // update matrix A
  A << t2 + in1[1], 0.0, 0.0, t2 - in1[1] * in1[1];
}

// End of code generation (matrixFunction.cpp)
