function coriolis = coriolis_biped(in1)
%CORIOLIS_BIPED
%    CORIOLIS = CORIOLIS_BIPED(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    05-Feb-2024 12:22:54

dq_hip_l = in1(16,:);
dq_hip_r = in1(13,:);
dq_knee_l = in1(17,:);
dq_knee_r = in1(14,:);
dth = in1(12,:);
q_hip_l = in1(7,:);
q_hip_r = in1(4,:);
q_knee_l = in1(8,:);
q_knee_r = in1(5,:);
th = in1(3,:);
t2 = sin(q_knee_l);
t3 = sin(q_knee_r);
t4 = q_hip_l+th;
t5 = q_hip_r+th;
t6 = dq_hip_l.^2;
t7 = dq_hip_r.^2;
t8 = dq_knee_l.^2;
t9 = dq_knee_r.^2;
t10 = dth.*2.0;
t11 = dth.^2;
t12 = cos(t4);
t13 = cos(t5);
t14 = q_knee_l+t4;
t15 = q_knee_r+t5;
t16 = sin(t4);
t17 = sin(t5);
t18 = cos(t14);
t19 = cos(t15);
t20 = sin(t14);
t21 = sin(t15);
coriolis = [t6.*t16.*(-1.71e+2./1.0e+2)-t7.*t17.*(1.71e+2./1.0e+2)-t6.*t20.*(2.7e+1./2.5e+1)-t11.*t16.*(1.71e+2./1.0e+2)-t7.*t21.*(2.7e+1./2.5e+1)-t8.*t20.*(2.7e+1./2.5e+1)-t11.*t17.*(1.71e+2./1.0e+2)-t9.*t21.*(2.7e+1./2.5e+1)-t11.*t20.*(2.7e+1./2.5e+1)-t11.*t21.*(2.7e+1./2.5e+1)+t11.*sin(th).*(2.1e+1./2.0e+1)-dq_hip_l.*dq_knee_l.*t20.*(5.4e+1./2.5e+1)-dq_hip_r.*dq_knee_r.*t21.*(5.4e+1./2.5e+1)-dq_hip_l.*dth.*t16.*(1.71e+2./5.0e+1)-dq_hip_l.*dth.*t20.*(5.4e+1./2.5e+1)-dq_hip_r.*dth.*t17.*(1.71e+2./5.0e+1)-dq_hip_r.*dth.*t21.*(5.4e+1./2.5e+1)-dq_knee_l.*dth.*t20.*(5.4e+1./2.5e+1)-dq_knee_r.*dth.*t21.*(5.4e+1./2.5e+1);t6.*t12.*(1.71e+2./1.0e+2)+t7.*t13.*(1.71e+2./1.0e+2)+t11.*t12.*(1.71e+2./1.0e+2)+t6.*t18.*(2.7e+1./2.5e+1)+t11.*t13.*(1.71e+2./1.0e+2)+t7.*t19.*(2.7e+1./2.5e+1)+t8.*t18.*(2.7e+1./2.5e+1)+t9.*t19.*(2.7e+1./2.5e+1)+t11.*t18.*(2.7e+1./2.5e+1)+t11.*t19.*(2.7e+1./2.5e+1)-t11.*cos(th).*(2.1e+1./2.0e+1)+dq_hip_l.*dq_knee_l.*t18.*(5.4e+1./2.5e+1)+dq_hip_r.*dq_knee_r.*t19.*(5.4e+1./2.5e+1)+dq_hip_l.*dth.*t12.*(1.71e+2./5.0e+1)+dq_hip_l.*dth.*t18.*(5.4e+1./2.5e+1)+dq_hip_r.*dth.*t13.*(1.71e+2./5.0e+1)+dq_hip_r.*dth.*t19.*(5.4e+1./2.5e+1)+dq_knee_l.*dth.*t18.*(5.4e+1./2.5e+1)+dq_knee_r.*dth.*t19.*(5.4e+1./2.5e+1);t2.*t8.*(-1.89e+2./6.25e+2)-t3.*t9.*(1.89e+2./6.25e+2)-dq_hip_l.*dq_knee_l.*t2.*(3.78e+2./6.25e+2)-dq_hip_r.*dq_knee_r.*t3.*(3.78e+2./6.25e+2)-dq_knee_l.*dth.*t2.*(3.78e+2./6.25e+2)-dq_knee_r.*dth.*t3.*(3.78e+2./6.25e+2);dq_knee_r.*t3.*(dq_hip_r.*2.0+dq_knee_r+t10).*(-1.89e+2./6.25e+2);t3.*(dq_hip_r+dth).^2.*(1.89e+2./6.25e+2);0.0;dq_knee_l.*t2.*(dq_hip_l.*2.0+dq_knee_l+t10).*(-1.89e+2./6.25e+2);t2.*(dq_hip_l+dth).^2.*(1.89e+2./6.25e+2);0.0];
