function gravity = grav_biped(in1)
%GRAV_BIPED
%    GRAVITY = GRAV_BIPED(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    05-Feb-2024 12:22:54

q_hip_l = in1(7,:);
q_hip_r = in1(4,:);
q_knee_l = in1(8,:);
q_knee_r = in1(5,:);
th = in1(3,:);
t2 = q_hip_l+th;
t3 = q_hip_r+th;
t4 = q_knee_l+t2;
t5 = q_knee_r+t3;
t6 = sin(t2);
t7 = sin(t3);
t8 = sin(t4);
t9 = sin(t5);
t10 = t6.*9.9081;
t11 = t7.*9.9081;
t12 = t8.*3.2373;
t13 = t9.*3.2373;
gravity = [0.0;9.81e+2./4.0;t10+t11+t12+t13-sin(th).*1.03005e+1;t11+t13;t13;0.0;t10+t12;t12;0.0];
