function gravity = grav_biped_toe(in1)
%GRAV_BIPED_TOE
%    GRAVITY = GRAV_BIPED_TOE(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    11-Mar-2024 14:00:06

q_ankle_l = in1(10,:);
q_ankle_r = in1(6,:);
q_hip_l = in1(8,:);
q_hip_r = in1(4,:);
q_knee_l = in1(9,:);
q_knee_r = in1(5,:);
q_toe_l = in1(11,:);
q_toe_r = in1(7,:);
th = in1(3,:);
t2 = q_hip_l+th;
t3 = q_hip_r+th;
t4 = q_knee_l+t2;
t5 = q_knee_r+t3;
t6 = sin(t2);
t7 = sin(t3);
t8 = q_ankle_l+t4;
t9 = q_ankle_r+t5;
t10 = sin(t4);
t11 = sin(t5);
t18 = t6.*1.928646e+1;
t19 = t7.*1.928646e+1;
t12 = cos(t8);
t13 = cos(t9);
t14 = q_toe_l+t8;
t15 = q_toe_r+t9;
t25 = t10.*8.50527;
t26 = t11.*8.50527;
t16 = sin(t15);
t17 = cos(t14);
t22 = t12.*2.40345e-1;
t23 = t13.*2.40345e-1;
t20 = t17.*6.867e-2;
t21 = t16.*6.867e-2;
t24 = -t21;
gravity = [0.0;3.19806e+2;t18+t19+t20+t22+t23+t24+t25+t26-sin(th).*1.03005e+1;t19+t23+t24+t26;t23+t24+t26;t23+t24;t24;t18+t20+t22+t25;t20+t22+t25;t20+t22;t20];
