function A = matrixFunction(in1)
%MATRIXFUNCTION
%    A = MATRIXFUNCTION(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    05-Feb-2024 12:41:46

x = in1(1,:);
y = in1(2,:);
t2 = x.^2;
A = reshape([t2+y,0.0,0.0,t2-y.^2],[2,2]);
