function COM = CoM_biped(in1)
%COM_BIPED
%    COM = COM_BIPED(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    04-Jul-2024 15:09:23

dq_hip_l = in1(13,:);
dq_hip_r = in1(11,:);
dq_knee_l = in1(14,:);
dq_knee_r = in1(12,:);
dth = in1(10,:);
dx = in1(8,:);
dy = in1(9,:);
q_hip_l = in1(6,:);
q_hip_r = in1(4,:);
q_knee_l = in1(7,:);
q_knee_r = in1(5,:);
th = in1(3,:);
x = in1(1,:);
y = in1(2,:);
t2 = cos(th);
t3 = sin(th);
t4 = q_hip_l+th;
t5 = q_hip_r+th;
t6 = cos(t4);
t7 = cos(t5);
t8 = q_knee_l+t4;
t9 = q_knee_r+t5;
t10 = sin(t4);
t11 = sin(t5);
t16 = t2./3.2e+1;
t17 = t3./3.2e+1;
t12 = cos(t8);
t13 = cos(t9);
t14 = sin(t8);
t15 = sin(t9);
t18 = -t17;
t23 = t6.*(2.9e+1./8.0e+2);
t24 = t7.*(2.9e+1./8.0e+2);
t25 = t10.*(2.9e+1./8.0e+2);
t26 = t11.*(2.9e+1./8.0e+2);
t19 = t12.*(3.0./4.0e+2);
t20 = t13.*(3.0./4.0e+2);
t21 = t14.*(3.0./4.0e+2);
t22 = t15.*(3.0./4.0e+2);
COM = [t18+t21+t22+t25+t26+x;t16-t19-t20-t23-t24+y;dx+dq_hip_l.*(t19+t23)+dq_hip_r.*(t20+t24)+dq_knee_l.*t19+dq_knee_r.*t20+dth.*(-t16+t19+t20+t23+t24);dy+dq_hip_l.*(t21+t25)+dq_hip_r.*(t22+t26)+dq_knee_l.*t21+dq_knee_r.*t22+dth.*(t18+t21+t22+t25+t26)];
