function E = energy_biped(in1)
%ENERGY_BIPED
%    E = ENERGY_BIPED(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    04-Jul-2024 15:09:22

dq_hip_l = in1(13,:);
dq_hip_r = in1(11,:);
dq_knee_l = in1(14,:);
dq_knee_r = in1(12,:);
dth = in1(10,:);
dx = in1(8,:);
dy = in1(9,:);
q_hip_l = in1(6,:);
q_hip_r = in1(4,:);
q_knee_l = in1(7,:);
q_knee_r = in1(5,:);
th = in1(3,:);
y = in1(2,:);
t2 = cos(th);
t3 = q_hip_l+th;
t4 = q_hip_r+th;
t5 = cos(t3);
t6 = cos(t4);
t7 = q_knee_l+t3;
t8 = q_knee_r+t4;
t9 = sin(t3);
t10 = sin(t4);
t11 = cos(t7);
t12 = cos(t8);
t13 = sin(t7);
t14 = sin(t8);
t15 = t5.*(7.0./2.5e+1);
t16 = t6.*(7.0./2.5e+1);
t17 = t9.*(7.0./2.5e+1);
t18 = t10.*(7.0./2.5e+1);
t19 = t11.*(3.0./2.5e+1);
t20 = t12.*(3.0./2.5e+1);
t21 = t13.*(3.0./2.5e+1);
t22 = t14.*(3.0./2.5e+1);
t23 = t17+t21;
t24 = t18+t22;
t25 = t15+t19;
t26 = t16+t20;
E = t2.*7.3575-t5.*8.5347-t6.*8.5347-t11.*1.7658-t12.*1.7658+y.*2.3544e+2+(dx-(dth.*t2)./2.0e+1).^2.*(1.5e+1./2.0)+(dq_hip_l+dth).^2./4.0e+1+(dq_hip_r+dth).^2./4.0e+1+(dx+dq_hip_l.*t5.*(3.0./2.0e+1)+dth.*t5.*(3.0./2.0e+1)).^2.*(3.0./2.0)+(dx+dq_hip_r.*t6.*(3.0./2.0e+1)+dth.*t6.*(3.0./2.0e+1)).^2.*(3.0./2.0)+(dy+dq_hip_l.*t9.*(3.0./2.0e+1)+dth.*t9.*(3.0./2.0e+1)).^2.*(3.0./2.0)+(dy+dq_hip_r.*t10.*(3.0./2.0e+1)+dth.*t10.*(3.0./2.0e+1)).^2.*(3.0./2.0)+dth.^2.*(3.0./2.0e+1)+(dx+dq_hip_l.*t25+dq_knee_l.*t19+dth.*t25).^2.*(3.0./4.0)+(dx+dq_hip_r.*t26+dq_knee_r.*t20+dth.*t26).^2.*(3.0./4.0)+(dy+dq_hip_l.*t23+dq_knee_l.*t21+dth.*t23).^2.*(3.0./4.0)+(dy+dq_hip_r.*t24+dq_knee_r.*t22+dth.*t24).^2.*(3.0./4.0)+(dy-(dth.*sin(th))./2.0e+1).^2.*(1.5e+1./2.0)+(dq_hip_l+dq_knee_l+dth).^2./1.0e+2+(dq_hip_r+dq_knee_r+dth).^2./1.0e+2;
