function gravity = grav_biped(in1)
%GRAV_BIPED
%    GRAVITY = GRAV_BIPED(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    04-Jul-2024 15:09:22

q_hip_l = in1(6,:);
q_hip_r = in1(4,:);
q_knee_l = in1(7,:);
q_knee_r = in1(5,:);
th = in1(3,:);
t2 = q_hip_l+th;
t3 = q_hip_r+th;
t4 = q_knee_l+t2;
t5 = q_knee_r+t3;
t6 = sin(t2);
t7 = sin(t3);
t8 = sin(t4);
t9 = sin(t5);
t12 = t6.*8.5347;
t13 = t7.*8.5347;
t10 = t8.*1.7658;
t11 = t9.*1.7658;
gravity = [0.0;2.3544e+2;t10+t11+t12+t13-sin(th).*7.3575;t11+t13;t11;t10+t12;t10];
