function keypoints_vel = keypoints_vel_biped(in1)
%KEYPOINTS_VEL_BIPED
%    KEYPOINTS_VEL = KEYPOINTS_VEL_BIPED(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    04-Jul-2024 15:09:23

dq_hip_l = in1(13,:);
dq_hip_r = in1(11,:);
dq_knee_l = in1(14,:);
dq_knee_r = in1(12,:);
dth = in1(10,:);
dx = in1(8,:);
dy = in1(9,:);
q_hip_l = in1(6,:);
q_hip_r = in1(4,:);
q_knee_l = in1(7,:);
q_knee_r = in1(5,:);
th = in1(3,:);
t2 = q_hip_l+th;
t3 = q_hip_r+th;
t4 = cos(t2);
t5 = cos(t3);
t6 = q_knee_l+t2;
t7 = q_knee_r+t3;
t8 = sin(t2);
t9 = sin(t3);
t10 = cos(t6);
t11 = cos(t7);
t12 = sin(t6);
t13 = sin(t7);
t14 = t4.*(7.0./2.5e+1);
t15 = t5.*(7.0./2.5e+1);
t16 = t8.*(7.0./2.5e+1);
t17 = t9.*(7.0./2.5e+1);
t18 = t10.*(3.0./1.0e+1);
t19 = t11.*(3.0./1.0e+1);
t20 = t12.*(3.0./1.0e+1);
t21 = t13.*(3.0./1.0e+1);
t22 = t16+t20;
t23 = t17+t21;
t24 = t14+t18;
t25 = t15+t19;
keypoints_vel = reshape([dx,dy,dx+dq_hip_r.*t15+dth.*t15,dy+dq_hip_r.*t17+dth.*t17,dx+dq_hip_r.*t25+dq_knee_r.*t19+dth.*t25,dy+dq_hip_r.*t23+dq_knee_r.*t21+dth.*t23,dx+dq_hip_l.*t14+dth.*t14,dy+dq_hip_l.*t16+dth.*t16,dx+dq_hip_l.*t24+dq_knee_l.*t18+dth.*t24,dy+dq_hip_l.*t22+dq_knee_l.*t20+dth.*t22,dx-dth.*cos(th).*(3.0./1.0e+1),dy-dth.*sin(th).*(3.0./1.0e+1)],[2,6]);
