function COM = CoM_biped(in1)
%COM_BIPED
%    COM = COM_BIPED(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    03-Jul-2024 12:50:19

dq_hip_l = in1(16,:);
dq_hip_r = in1(13,:);
dq_knee_l = in1(17,:);
dq_knee_r = in1(14,:);
dth = in1(12,:);
dx = in1(10,:);
dy = in1(11,:);
q_hip_l = in1(7,:);
q_hip_r = in1(4,:);
q_knee_l = in1(8,:);
q_knee_r = in1(5,:);
th = in1(3,:);
x = in1(1,:);
y = in1(2,:);
t2 = cos(th);
t3 = sin(th);
t4 = q_hip_l+th;
t5 = q_hip_r+th;
t6 = cos(t4);
t7 = cos(t5);
t8 = q_knee_l+t4;
t9 = q_knee_r+t5;
t10 = sin(t4);
t11 = sin(t5);
t16 = t2.*(2.1e+1./5.0e+2);
t17 = t3.*(2.1e+1./5.0e+2);
t12 = cos(t8);
t13 = cos(t9);
t14 = sin(t8);
t15 = sin(t9);
t18 = -t17;
t19 = t6.*4.04e-2;
t20 = t7.*4.04e-2;
t21 = t10.*4.04e-2;
t22 = t11.*4.04e-2;
t23 = t12.*1.32e-2;
t24 = t13.*1.32e-2;
t25 = t14.*1.32e-2;
t26 = t15.*1.32e-2;
COM = [t18+t21+t22+t25+t26+x;t16-t19-t20-t23-t24+y;dx+dq_hip_l.*(t19+t23)+dq_hip_r.*(t20+t24)+dq_knee_l.*t23+dq_knee_r.*t24+dth.*(-t16+t19+t20+t23+t24);dy+dq_hip_l.*(t21+t25)+dq_hip_r.*(t22+t26)+dq_knee_l.*t25+dq_knee_r.*t26+dth.*(t18+t21+t22+t25+t26)];
