function E = energy_biped(in1)
%ENERGY_BIPED
%    E = ENERGY_BIPED(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    03-Jul-2024 12:50:18

dq_hip_l = in1(16,:);
dq_hip_r = in1(13,:);
dq_knee_l = in1(17,:);
dq_knee_r = in1(14,:);
dq_ankle_l = in1(18,:);
dq_ankle_r = in1(15,:);
dth = in1(12,:);
dx = in1(10,:);
dy = in1(11,:);
q_hip_l = in1(7,:);
q_hip_r = in1(4,:);
q_knee_l = in1(8,:);
q_knee_r = in1(5,:);
th = in1(3,:);
y = in1(2,:);
t2 = cos(th);
t3 = q_hip_l+th;
t4 = q_hip_r+th;
t5 = cos(t3);
t6 = cos(t4);
t7 = q_knee_l+t3;
t8 = q_knee_r+t4;
t9 = sin(t3);
t10 = sin(t4);
t11 = cos(t7);
t12 = cos(t8);
t13 = sin(t7);
t14 = sin(t8);
t15 = t5.*(7.0./2.5e+1);
t16 = t6.*(7.0./2.5e+1);
t17 = t9.*(7.0./2.5e+1);
t18 = t10.*(7.0./2.5e+1);
t19 = t11.*(3.0./1.0e+1);
t20 = t12.*(3.0./1.0e+1);
t21 = t11.*(3.0./2.5e+1);
t22 = t12.*(3.0./2.5e+1);
t23 = t13.*(3.0./1.0e+1);
t24 = t14.*(3.0./1.0e+1);
t25 = t13.*(3.0./2.5e+1);
t26 = t14.*(3.0./2.5e+1);
t27 = t17+t23;
t28 = t17+t25;
t29 = t18+t24;
t30 = t18+t26;
t31 = t15+t19;
t32 = t15+t21;
t33 = t16+t20;
t34 = t16+t22;
E = t2.*1.03005e+1-t5.*9.9081-t6.*9.9081-t11.*3.2373-t12.*3.2373+y.*(9.81e+2./4.0)+(dq_hip_l+dq_knee_l+dq_ankle_l+dth).^2./2.5e+2+(dq_hip_r+dq_knee_r+dq_ankle_r+dth).^2./2.5e+2+(dx-dth.*t2.*(7.0./1.0e+2)).^2.*(1.5e+1./2.0)+(dq_hip_l+dth).^2./4.0e+1+(dq_hip_r+dth).^2./4.0e+1+(dx+dq_hip_l.*t5.*(3.0./2.0e+1)+dth.*t5.*(3.0./2.0e+1)).^2.*(3.0./2.0)+(dx+dq_hip_r.*t6.*(3.0./2.0e+1)+dth.*t6.*(3.0./2.0e+1)).^2.*(3.0./2.0)+(dy+dq_hip_l.*t9.*(3.0./2.0e+1)+dth.*t9.*(3.0./2.0e+1)).^2.*(3.0./2.0)+(dy+dq_hip_r.*t10.*(3.0./2.0e+1)+dth.*t10.*(3.0./2.0e+1)).^2.*(3.0./2.0)+dth.^2./2.0e+1+(dx+dq_hip_l.*t31+dq_knee_l.*t19+dth.*t31).^2.*(3.0./2.0)+(dx+dq_hip_l.*t32+dq_knee_l.*t21+dth.*t32).^2.*(3.0./4.0)+(dx+dq_hip_r.*t33+dq_knee_r.*t20+dth.*t33).^2.*(3.0./2.0)+(dx+dq_hip_r.*t34+dq_knee_r.*t22+dth.*t34).^2.*(3.0./4.0)+(dy+dq_hip_l.*t27+dq_knee_l.*t23+dth.*t27).^2.*(3.0./2.0)+(dy+dq_hip_l.*t28+dq_knee_l.*t25+dth.*t28).^2.*(3.0./4.0)+(dy+dq_hip_r.*t29+dq_knee_r.*t24+dth.*t29).^2.*(3.0./2.0)+(dy+dq_hip_r.*t30+dq_knee_r.*t26+dth.*t30).^2.*(3.0./4.0)+(dy-dth.*sin(th).*(7.0./1.0e+2)).^2.*(1.5e+1./2.0)+(dq_hip_l+dq_knee_l+dth).^2./1.0e+2+(dq_hip_r+dq_knee_r+dth).^2./1.0e+2;
