function keypoints = keypoints_biped(in1)
%KEYPOINTS_BIPED
%    KEYPOINTS = KEYPOINTS_BIPED(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    03-Jul-2024 12:50:19

q_ankle_l = in1(9,:);
q_ankle_r = in1(6,:);
q_hip_l = in1(7,:);
q_hip_r = in1(4,:);
q_knee_l = in1(8,:);
q_knee_r = in1(5,:);
th = in1(3,:);
x = in1(1,:);
y = in1(2,:);
t2 = q_hip_l+th;
t3 = q_hip_r+th;
t14 = pi./2.0;
t4 = cos(t2);
t5 = cos(t3);
t6 = q_knee_l+t2;
t7 = q_knee_r+t3;
t8 = sin(t2);
t9 = sin(t3);
t15 = -t14;
t10 = cos(t6);
t11 = cos(t7);
t12 = sin(t6);
t13 = sin(t7);
t16 = t4.*(7.0./2.5e+1);
t17 = t5.*(7.0./2.5e+1);
t18 = t8.*(7.0./2.5e+1);
t19 = t9.*(7.0./2.5e+1);
t26 = q_ankle_l+t6+t14;
t27 = q_ankle_r+t7+t14;
t30 = q_ankle_l+t6+t15;
t31 = q_ankle_r+t7+t15;
t20 = -t16;
t21 = -t17;
t22 = t10.*(3.0./1.0e+1);
t23 = t11.*(3.0./1.0e+1);
t24 = t12.*(3.0./1.0e+1);
t25 = t13.*(3.0./1.0e+1);
t28 = -t22;
t29 = -t23;
keypoints = reshape([x,y,t19+x,t21+y,t19+t25+x,t21+t29+y,t19+t25+x+sin(t27).*(2.0./2.5e+1),t21+t29+y-cos(t27).*(2.0./2.5e+1),t19+t25+x+sin(t31).*(2.0./2.5e+1),t21+t29+y-cos(t31).*(2.0./2.5e+1),t18+x,t20+y,t18+t24+x,t20+t28+y,t18+t24+x+sin(t26).*(2.0./2.5e+1),t20+t28+y-cos(t26).*(2.0./2.5e+1),t18+t24+x+sin(t30).*(2.0./2.5e+1),t20+t28+y-cos(t30).*(2.0./2.5e+1),x-sin(th).*(3.0./1.0e+1),y+cos(th).*(3.0./1.0e+1)],[2,10]);
