# CMake generated Testfile for 
# Source directory: /home/qh/Desktop/mujoco-daros/test/plugin/elasticity
# Build directory: /home/qh/Desktop/mujoco-daros/test/plugin/elasticity
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ElasticityTest.FlexCompatibility "/home/qh/Desktop/mujoco-daros/bin/elasticity_test" "--gtest_filter=ElasticityTest.FlexCompatibility")
set_tests_properties(ElasticityTest.FlexCompatibility PROPERTIES  ENVIRONMENT "MUJOCO_PLUGIN_DIR=/home/qh/Desktop/mujoco-daros/lib" WORKING_DIRECTORY "/home/qh/Desktop/mujoco-daros/test" _BACKTRACE_TRIPLES "/usr/share/cmake-3.22/Modules/GoogleTest.cmake;400;add_test;/home/qh/Desktop/mujoco-daros/test/CMakeLists.txt;37;gtest_add_tests;/home/qh/Desktop/mujoco-daros/test/plugin/elasticity/CMakeLists.txt;15;mujoco_test;/home/qh/Desktop/mujoco-daros/test/plugin/elasticity/CMakeLists.txt;0;")
add_test(ElasticityTest.ElasticEnergyShell "/home/qh/Desktop/mujoco-daros/bin/elasticity_test" "--gtest_filter=ElasticityTest.ElasticEnergyShell")
set_tests_properties(ElasticityTest.ElasticEnergyShell PROPERTIES  ENVIRONMENT "MUJOCO_PLUGIN_DIR=/home/qh/Desktop/mujoco-daros/lib" WORKING_DIRECTORY "/home/qh/Desktop/mujoco-daros/test" _BACKTRACE_TRIPLES "/usr/share/cmake-3.22/Modules/GoogleTest.cmake;400;add_test;/home/qh/Desktop/mujoco-daros/test/CMakeLists.txt;37;gtest_add_tests;/home/qh/Desktop/mujoco-daros/test/plugin/elasticity/CMakeLists.txt;15;mujoco_test;/home/qh/Desktop/mujoco-daros/test/plugin/elasticity/CMakeLists.txt;0;")
add_test(PluginTest.ElasticEnergyMembrane "/home/qh/Desktop/mujoco-daros/bin/elasticity_test" "--gtest_filter=PluginTest.ElasticEnergyMembrane")
set_tests_properties(PluginTest.ElasticEnergyMembrane PROPERTIES  ENVIRONMENT "MUJOCO_PLUGIN_DIR=/home/qh/Desktop/mujoco-daros/lib" WORKING_DIRECTORY "/home/qh/Desktop/mujoco-daros/test" _BACKTRACE_TRIPLES "/usr/share/cmake-3.22/Modules/GoogleTest.cmake;400;add_test;/home/qh/Desktop/mujoco-daros/test/CMakeLists.txt;37;gtest_add_tests;/home/qh/Desktop/mujoco-daros/test/plugin/elasticity/CMakeLists.txt;15;mujoco_test;/home/qh/Desktop/mujoco-daros/test/plugin/elasticity/CMakeLists.txt;0;")
add_test(ElasticityTest.InvalidThickness "/home/qh/Desktop/mujoco-daros/bin/elasticity_test" "--gtest_filter=ElasticityTest.InvalidThickness")
set_tests_properties(ElasticityTest.InvalidThickness PROPERTIES  ENVIRONMENT "MUJOCO_PLUGIN_DIR=/home/qh/Desktop/mujoco-daros/lib" WORKING_DIRECTORY "/home/qh/Desktop/mujoco-daros/test" _BACKTRACE_TRIPLES "/usr/share/cmake-3.22/Modules/GoogleTest.cmake;400;add_test;/home/qh/Desktop/mujoco-daros/test/CMakeLists.txt;37;gtest_add_tests;/home/qh/Desktop/mujoco-daros/test/plugin/elasticity/CMakeLists.txt;15;mujoco_test;/home/qh/Desktop/mujoco-daros/test/plugin/elasticity/CMakeLists.txt;0;")
add_test(ElasticityTest.ElasticEnergySolid "/home/qh/Desktop/mujoco-daros/bin/elasticity_test" "--gtest_filter=ElasticityTest.ElasticEnergySolid")
set_tests_properties(ElasticityTest.ElasticEnergySolid PROPERTIES  ENVIRONMENT "MUJOCO_PLUGIN_DIR=/home/qh/Desktop/mujoco-daros/lib" WORKING_DIRECTORY "/home/qh/Desktop/mujoco-daros/test" _BACKTRACE_TRIPLES "/usr/share/cmake-3.22/Modules/GoogleTest.cmake;400;add_test;/home/qh/Desktop/mujoco-daros/test/CMakeLists.txt;37;gtest_add_tests;/home/qh/Desktop/mujoco-daros/test/plugin/elasticity/CMakeLists.txt;15;mujoco_test;/home/qh/Desktop/mujoco-daros/test/plugin/elasticity/CMakeLists.txt;0;")
add_test(ElasticityTest.CantileverIntoCircle "/home/qh/Desktop/mujoco-daros/bin/elasticity_test" "--gtest_filter=ElasticityTest.CantileverIntoCircle")
set_tests_properties(ElasticityTest.CantileverIntoCircle PROPERTIES  ENVIRONMENT "MUJOCO_PLUGIN_DIR=/home/qh/Desktop/mujoco-daros/lib" WORKING_DIRECTORY "/home/qh/Desktop/mujoco-daros/test" _BACKTRACE_TRIPLES "/usr/share/cmake-3.22/Modules/GoogleTest.cmake;400;add_test;/home/qh/Desktop/mujoco-daros/test/CMakeLists.txt;37;gtest_add_tests;/home/qh/Desktop/mujoco-daros/test/plugin/elasticity/CMakeLists.txt;15;mujoco_test;/home/qh/Desktop/mujoco-daros/test/plugin/elasticity/CMakeLists.txt;0;")
add_test(ElasticityTest.InvalidTxtAttribute "/home/qh/Desktop/mujoco-daros/bin/elasticity_test" "--gtest_filter=ElasticityTest.InvalidTxtAttribute")
set_tests_properties(ElasticityTest.InvalidTxtAttribute PROPERTIES  ENVIRONMENT "MUJOCO_PLUGIN_DIR=/home/qh/Desktop/mujoco-daros/lib" WORKING_DIRECTORY "/home/qh/Desktop/mujoco-daros/test" _BACKTRACE_TRIPLES "/usr/share/cmake-3.22/Modules/GoogleTest.cmake;400;add_test;/home/qh/Desktop/mujoco-daros/test/CMakeLists.txt;37;gtest_add_tests;/home/qh/Desktop/mujoco-daros/test/plugin/elasticity/CMakeLists.txt;15;mujoco_test;/home/qh/Desktop/mujoco-daros/test/plugin/elasticity/CMakeLists.txt;0;")
add_test(ElasticityTest.InvalidMixedAttribute "/home/qh/Desktop/mujoco-daros/bin/elasticity_test" "--gtest_filter=ElasticityTest.InvalidMixedAttribute")
set_tests_properties(ElasticityTest.InvalidMixedAttribute PROPERTIES  ENVIRONMENT "MUJOCO_PLUGIN_DIR=/home/qh/Desktop/mujoco-daros/lib" WORKING_DIRECTORY "/home/qh/Desktop/mujoco-daros/test" _BACKTRACE_TRIPLES "/usr/share/cmake-3.22/Modules/GoogleTest.cmake;400;add_test;/home/qh/Desktop/mujoco-daros/test/CMakeLists.txt;37;gtest_add_tests;/home/qh/Desktop/mujoco-daros/test/plugin/elasticity/CMakeLists.txt;15;mujoco_test;/home/qh/Desktop/mujoco-daros/test/plugin/elasticity/CMakeLists.txt;0;")
add_test(ElasticityTest.ValidAttributes "/home/qh/Desktop/mujoco-daros/bin/elasticity_test" "--gtest_filter=ElasticityTest.ValidAttributes")
set_tests_properties(ElasticityTest.ValidAttributes PROPERTIES  ENVIRONMENT "MUJOCO_PLUGIN_DIR=/home/qh/Desktop/mujoco-daros/lib" WORKING_DIRECTORY "/home/qh/Desktop/mujoco-daros/test" _BACKTRACE_TRIPLES "/usr/share/cmake-3.22/Modules/GoogleTest.cmake;400;add_test;/home/qh/Desktop/mujoco-daros/test/CMakeLists.txt;37;gtest_add_tests;/home/qh/Desktop/mujoco-daros/test/plugin/elasticity/CMakeLists.txt;15;mujoco_test;/home/qh/Desktop/mujoco-daros/test/plugin/elasticity/CMakeLists.txt;0;")
