# Normal Stand
# initial_rpy: [ 0., 0.08, 0.]
# initial_body_vel: [ 0., 0., 0., 0.6, -0.04, 0.]
initial_body_vel: [ 0., 0., 0., 0, 0, 0.]
# initial_body_pos: [ 0.0, 0., 0.721] # 0.581 + ground height

# initial_jpos: [ 0., 0.05, -0.5, 0.75, -0.35,    #two legs.
#                 0., -0.05, -0.5, 0.75, -0.35,
#                 0.0, 0.0, 0.0, 0.0, 
#                 0.0, 0.0, 0.0, 0.0]


# initial_body_pos: [ 0.0, 0., 0.579] # 0.581 + ground height
# initial_jpos: [ 0., 0.05, -1, 1.75, -0.85,    #two legs. 
#                 0., -0.05, -1, 1.75, -0.85,
#                 0.0, 0.0, 0.0, -0.5, 
#                 0.0, 0.0, 0.0, -0.5]

# initial_body_pos: [ 0.0, 0., 0.579] # 0.581 + ground height
# initial_jpos: [ 0., 0.05, -1, 1.75, -0.85,    #two legs. 
#                 0., -0.05, -1, 1.75, -0.85,
#                 0.0, 0.0, 0.0, 0.0, 
#                 0.0, 0.0, 0.0, 0.0]

initial_rpy: [ 0.0, 0.0, 0.0]

initial_body_pos: [ 0., 0., 0.58]

initial_jpos: [ 0.0, -0.1, -0.724757, 1.412282, -0.68752,
                0.0,  0.1, -0.724757, 1.412282, -0.68752,
                0.0, 0.0, 0.0, -1.1,
                0.0, 0.0, 0.0, -1.1]