function J_contact = J_biped(in1,in2)
%J_BIPED
%    J_CONTACT = J_BIPED(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    16-Jul-2024 22:53:26

l_shank = in2(2,:);
l_thigh = in2(1,:);
q_hip = in1(3,:);
q_knee = in1(4,:);
t2 = q_hip+q_knee;
t3 = cos(t2);
t4 = sin(t2);
t5 = l_shank.*t3;
t6 = l_shank.*t4;
J_contact = reshape([1.0,0.0,0.0,1.0,t5+l_thigh.*cos(q_hip),t6+l_thigh.*sin(q_hip),t5,t6],[2,4]);
