function keypoints = keypoints_biped(in1,in2)
%KEYPOINTS_BIPED
%    KEYPOINTS = KEYPOINTS_BIPED(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    16-Jul-2024 22:53:25

l_shank = in2(2,:);
l_thigh = in2(1,:);
q_hip = in1(3,:);
q_knee = in1(4,:);
x = in1(1,:);
y = in1(2,:);
t2 = cos(q_hip);
t3 = sin(q_hip);
t4 = q_hip+q_knee;
t5 = l_thigh.*t2;
t6 = l_thigh.*t3;
t7 = -t5;
keypoints = reshape([x,y,t6+x,t7+y,t6+x+l_shank.*sin(t4),t7+y-l_shank.*cos(t4)],[2,3]);
